<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Linear_Models.knit</title>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="syllabus.html">Course Syllabus</a>
</li>
<li>
  <a href="Fundamentals_of_Statistics.html">Fundamentals</a>
</li>
<li>
  <a href="Linear_Models.html">Linear Models</a>
</li>
<li>
  <a href="Maximum_Likelihood.html">Maximum Liklihood</a>
</li>
<li>
  <a href="Multilevel_Models.html">Multilevel Models</a>
</li>
<li>
  <a href="Comp_Intensive_Approaches.html">Resampling Methods</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<div id="linear-regression" class="section level1">
<h1><span class="header-section-number">1</span> Linear Regression</h1>
<p>Analysis with a one independent (X) and dependent variable (Y) is termed “Simple” linear regression.</p>
<div id="what-is-regression" class="section level2">
<h2><span class="header-section-number">1.1</span> What is Regression?</h2>
<ul>
<li><p>A way of predicting the value of one variable from another.</p></li>
<li><p>It is a model of the relationship between two variables.</p></li>
<li><p>The modeled relationship is linear.</p></li>
<li><p>Therefore, we describe the relationship using the equation for a straight line.</p></li>
</ul>
<p>To do the fitting and the hypothesis testing, we will evaluate the following quantities:</p>
<ul>
<li>Total sum of squares (TSS or <span class="math inline">\(SS_T\)</span>)</li>
<li>Model sum of squares (Regression SS, <span class="math inline">\(SS_M\)</span>)</li>
<li>Residual sum of squares (RSS or <span class="math inline">\(SS_R\)</span>)</li>
</ul>
<p>We will use these quantities to understand two things:</p>
<ol style="list-style-type: decimal">
<li><p>Is <span class="math inline">\(\beta_1 = 0\)</span> (using the confidence intervals)? We would like to know if <em>X</em> is a good predictor of <em>Y</em> and this is determined by evaluating the null hypothesis, <span class="math inline">\(\beta_1 = 0\)</span>.</p></li>
<li><p>Is the model significant (using an <em>F</em>-test)? Specifically does the fit of model fit the data better than does the null model (more on this below).</p></li>
</ol>
</div>
<div id="assumptions-of-simple-linear-regression" class="section level2">
<h2><span class="header-section-number">1.2</span> Assumptions of Simple Linear Regression</h2>
<ul>
<li><p>For each value of <em>X</em>, <em>Y</em> are randomly sampled and independent.</p></li>
<li><p>For any value of <em>X</em> in the population there exists a normal distribution of Y values</p></li>
<li><p>There is homogeneity of variance in the population. i.e. the variance of the normal distribution of <em>Y</em> values in population are equal for all of values of <em>X</em>.</p></li>
<li><p><em>X</em> is measured without error</p></li>
<li><p>The exptected value of <em>Y</em> at the <span class="math inline">\(i^{th}\)</span> value of <em>X</em> is <span class="math inline">\(E(Y_i)=\beta_0 + \beta_1X_i\)</span></p></li>
</ul>
</div>
<div id="model-for-linear-relationship-is-a-two-parameter-model" class="section level2">
<h2><span class="header-section-number">1.3</span> Model for Linear Relationship is a two-parameter model</h2>
<p>The first parameter is <span class="math inline">\(\beta_1\)</span></p>
<ul>
<li><p>Gradient (slope) of the regression line.</p></li>
<li><p>This indicates the direction of the relationship.</p></li>
</ul>
<p>The second parameter is <span class="math inline">\(\beta_0\)</span></p>
<ul>
<li><p>Intercept (value of <em>Y</em> when <em>X</em> = 0).</p></li>
<li><p>Location where the regression line crosses the <em>Y</em>-axis (ordinate).</p></li>
</ul>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
</div>
<div id="intercepts-and-gradients" class="section level2">
<h2><span class="header-section-number">1.4</span> Intercepts and Gradients</h2>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
</div>
<div id="the-method-of-least-squares" class="section level2">
<h2><span class="header-section-number">1.5</span> The Method of Least Squares</h2>
<p>This is the approach we will use for parameter estimation and inference in this course.</p>
<p>This figure shows a scatterplot of some data with a line representing the best fit model.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>This figure shows the residual (observed - expected) value of the best fit model.</p>
<p>Our task is to minimize the <span class="math inline">\(SS\)</span> value.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Let’s look at a some cases for alternatvie candidate model parameters:</p>
<p>Our task is to minimize the <span class="math inline">\(SS\)</span> value.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="sum-of-squares-components" class="section level2">
<h2><span class="header-section-number">1.6</span> Sum of Squares Components</h2>
<p>Once the best fit model is derived, we can make inference about the quality of the model (relative to the null model) and the hypothesis <span class="math inline">\(\beta_1 = 0\)</span>.</p>
<p>Let’s take a close look at the three sum of squares components.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
</div>
<div id="total-ss-sst-sst" class="section level2">
<h2><span class="header-section-number">1.7</span> Total SS (SS<sub>T</sub>, SST)</h2>
<p>Total variability (variability between scores and the mean) in the observations.</p>
<ul>
<li><p>TSS is the sum of the squared residuals when the most basic model is applied to the data.</p></li>
<li><p>How good is the mean as a model to the observed data?</p></li>
<li><p>Lets consider the mean of <em>Y</em> to be the null model:</p></li>
<li><p>SS<sub>T</sub> uses the differences between the observed data and the mean value of <em>Y</em> (the null model)</p></li>
<li><p><span class="math inline">\(TSS =\sum(Y_i - \bar{Y})^2\)</span></p></li>
</ul>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="residual-ss-or-error-ss-ssr" class="section level2">
<h2><span class="header-section-number">1.8</span> Residual SS or Error SS (SS<sub>R</sub>)</h2>
<p>SS<sub>R</sub> is the error that is derived between the regression model and the actual data).</p>
<ul>
<li><p>Difference between the observation and the model</p></li>
<li><p>Represents the degree of inaccuracy when fitting the model to the data.</p></li>
<li><p>Residual/error variability (variability between the regression model and the actual data).</p></li>
<li><p><span class="math inline">\(RSS =\sum(Y_i - \hat{Y})^2\)</span></p></li>
</ul>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="model-ss-or-regression-ss-ssm" class="section level2">
<h2><span class="header-section-number">1.9</span> Model SS or Regression SS (SS<sub>M</sub>)</h2>
<p>SS<sub>M</sub> is the difference between the prediction from the regression model and the mean (null model).</p>
<ul>
<li><p>This is the improvement we get from fitting the model to the data relative to the null model.</p></li>
<li><p><span class="math inline">\(SS_M=\sum(\hat{Y}_i - \bar{Y})^2\)</span></p></li>
</ul>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="the-ss-components-are-related-and-useful-for-understanding-the-model" class="section level2">
<h2><span class="header-section-number">1.10</span> The SS components are related and useful for understanding the model</h2>
<p>The total variabilty is partitioned between the model and the residual:</p>
<p><span class="math inline">\(SS_T = SS_M + SS_R\)</span></p>
<p>We calculate the sum of squares components to evaluate the amount of systematic variance (regression/model) and the amount of unsystematic (residual) variance.</p>
<p>If we have a good model, the total variance in the observations will be described to a great extent by the model.</p>
<p>The proportion of improvement due to the model.</p>
<ul>
<li><span class="math inline">\(R^2 = SS_M/SS_T\)</span>, percentage of variation explained by the model.</li>
</ul>
</div>
<div id="variance-ratio-test" class="section level2">
<h2><span class="header-section-number">1.11</span> Variance Ratio Test</h2>
<p>We will evalute the model using an <em>F</em> test - “termed variance ratio test”.</p>
<p>We will be evaluating the ratio of SSM and SSR.</p>
<ol style="list-style-type: decimal">
<li><p>We will use the SSM and SSR to calculate quantities “mean squares”</p></li>
<li><p>This will be done by dividing the SSM and SSR by their respective degrees of freedom (df). These terms can be expressed as averages, divided by df terms.</p></li>
</ol>
<ul>
<li><p>df for SSM (The number of parameters in the model - 1)</p></li>
<li><p>df for SSR (number of obs - number of parameters in the model)</p></li>
</ul>
<p>These quantities are called mean squares.</p>
<ul>
<li>Mean Squares Model; MS<sub>M</sub> = SS<sub>M</sub>/df<sub>M</sub></li>
<li>Mean Squares Residual: MS<sub>R</sub> = SS<sub>R</sub>/df<sub>R</sub></li>
</ul>
<p><em>F</em>-test is termed the “variance ratio test”</p>
<p><span class="math inline">\(F=\frac{MS_M}{MS_R}\)</span></p>
</div>
<div id="test-beta_1-0" class="section level2">
<h2><span class="header-section-number">1.12</span> Test <span class="math inline">\(\beta_1 = 0\)</span></h2>
<p>To test whether <span class="math inline">\(\beta_1 = 0\)</span> we will use the t-distribution.</p>
<p>After determining the model parameters values we can estimate the standard error of the slope paramter.</p>
<p>The approach is to determine the confidence interval of the slope (<span class="math inline">\(\beta_1\)</span>) for a given value of <span class="math inline">\(\alpha\)</span>.</p>
<p>Look at the following equation, what values will we need?</p>
<p><span class="math inline">\(SE_{\beta_1}=\frac {\sqrt{\frac{(\sum{{Y_i - \hat{Y_i}}})^2}{df}}}{\sqrt{\sum{(X_i - \bar{X})^2}}}\)</span></p>
<p><span class="math inline">\(SE_{\beta_1}=\frac {\sqrt{\frac{(\sum{{Y_i - \hat{Y_i}}})^2}{(n - 2)}}}{\sqrt{\sum{(X_i - \bar{X})^2}}}\)</span></p>
<p>Degrees of freedom: For simple linear regression (one independent and one dependent variable), the degrees of freedom (df) is equal to, n - 2.</p>
<p>Our calculated test statistic is:</p>
<p><span class="math inline">\(t = \frac{\beta_1}{SE_{\beta_1}}\)</span></p>
<p>We will compare this to the critical value:</p>
<p><span class="math inline">\(t_{\alpha, 2-tailed, df}\)</span></p>
</div>
<div id="worked-example" class="section level2">
<h2><span class="header-section-number">1.13</span> Worked Example</h2>
<table>
<thead>
<tr class="header">
<th>Age (days) (X)</th>
<th>Wing Length (cm) (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3.0</td>
<td>1.4</td>
</tr>
<tr class="even">
<td>4.0</td>
<td>1.5</td>
</tr>
<tr class="odd">
<td>5.0</td>
<td>2.2</td>
</tr>
<tr class="even">
<td>6.0</td>
<td>2.4</td>
</tr>
<tr class="odd">
<td>8.0</td>
<td>3.1</td>
</tr>
<tr class="even">
<td>9.0</td>
<td>3.2</td>
</tr>
<tr class="odd">
<td>10.0</td>
<td>3.2</td>
</tr>
<tr class="even">
<td>11.0</td>
<td>3.9</td>
</tr>
<tr class="odd">
<td>12.0</td>
<td>4.1</td>
</tr>
<tr class="even">
<td>14.0</td>
<td>4.7</td>
</tr>
<tr class="odd">
<td>15.0</td>
<td>4.5</td>
</tr>
<tr class="even">
<td>16.0</td>
<td>5.2</td>
</tr>
<tr class="odd">
<td>17.0</td>
<td>5.0</td>
</tr>
</tbody>
</table>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>We find that the TSS is = 19.65</p>
<p>We find that the Model SS = 19.13</p>
<table>
<colgroup>
<col width="25%" />
<col width="25%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th>Source of Variation</th>
<th>Sum of Squares (SS)</th>
<th>df</th>
<th>Mean Squares (MS)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total</td>
<td><span class="math inline">\(\sum(Y_i-\bar{Y})^2\)</span></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Model (or Regression)</td>
<td><span class="math inline">\(\sum(\hat{Y}_i-\bar{Y})^2\)</span></td>
<td>The number of parameters in the model - 1</td>
<td>SS<sub>M</sub>/df<sub>M</sub></td>
</tr>
<tr class="odd">
<td>Residual (or Error)</td>
<td><span class="math inline">\(\sum(Y_i-\hat{Y_i})^2\)</span></td>
<td>The number of obs - the number of parameters in the model</td>
<td>SS<sub>R</sub>/df<sub>R</sub></td>
</tr>
</tbody>
</table>
<div id="summary-of-the-calculations-for-model-fit" class="section level3">
<h3><span class="header-section-number">1.13.1</span> Summary of the Calculations for Model Fit</h3>
<p>We are falsifying the null hypothesis: <span class="math inline">\(H_0\)</span>: There is no statistically significant relationship between variables x and y.</p>
<table>
<thead>
<tr class="header">
<th>Source of Variance</th>
<th>SS</th>
<th>df</th>
<th>MS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total</td>
<td>19.65</td>
<td>12</td>
<td></td>
</tr>
<tr class="even">
<td>Model (or Regression)</td>
<td>19.13</td>
<td>1</td>
<td>19.13</td>
</tr>
<tr class="odd">
<td>Residual (or Error)</td>
<td>0.52</td>
<td>11</td>
<td>0.047</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(F=\frac{19.132214}{0.047701}=401.1\)</span></p>
<p><span class="math inline">\(F_{0.05(1),1.11} = 4.84\)</span></p>
<p>Therefore, reject H<sub>0</sub></p>
<p>P &lt; 0.0005</p>
</div>
</div>
<div id="regression-an-example" class="section level2">
<h2><span class="header-section-number">1.14</span> Regression: An Example</h2>
<p>A record company executive is interested in predicting record sales from advertising.</p>
<p>Data are:</p>
<ul>
<li>200 different album releases</li>
</ul>
<p>Outcome variable:</p>
<ul>
<li>Sales (CDs and downloads) in the week after release</li>
</ul>
<p>Predictor variable:</p>
<ul>
<li>The amount (in units of $1,000) spent promoting the record before release.</li>
</ul>
</div>
<div id="output-of-a-simple-regression" class="section level2">
<h2><span class="header-section-number">1.15</span> Output of a Simple Regression</h2>
<p>In R:</p>
<table>
<thead>
<tr class="header">
<th>Coefficients:</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t value</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(intercept)</td>
<td>134</td>
<td>7.53</td>
<td>17.799</td>
<td>&lt; <span class="math inline">\(2\times10^{-16}\)</span> ***</td>
</tr>
<tr class="even">
<td>Adverts</td>
<td>0.096</td>
<td>0.00963</td>
<td>9.979</td>
<td>&lt; <span class="math inline">\(2\times10^{-16}\)</span> ***</td>
</tr>
</tbody>
</table>
<ul>
<li>Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</li>
<li>Residual standard error: 65.99 on 198 degrees of freedom</li>
<li>Multiple R-squared: 0.3346, Adjusted R-squared: 0.3313</li>
<li>F-statistic: 99.59 on 1 and 198 df, p-value: &lt; 2.2e-16</li>
</ul>
</div>
<div id="using-the-model" class="section level2">
<h2><span class="header-section-number">1.16</span> Using the Model</h2>
<p>Expected Record Sales<sub>i</sub> = 134.14 + (0.096 x Advertising Budget<sub>i</sub>)</p>
<p>E(Record sales if Budget = 100) = 134.14 + (0.096 x 100)</p>
<p>E(Record sales if Budget = 100) = 143.75</p>
</div>
<div id="analysis-of-the-slope-coeffient" class="section level2">
<h2><span class="header-section-number">1.17</span> Analysis of the slope coeffient</h2>
<p>Using the fact that <span class="math inline">\(\beta_1\)</span> is approximately normally distributed in large samples, we can test the hypothesis that <span class="math inline">\(\beta_1 = 0\)</span>.</p>
<p>From our reading, we learned that the calculated value of the <em>t</em>-statistic is:</p>
<p><span class="math inline">\(t = \frac{\beta_{observed} - {\beta_{expected}}}{{SE_{\beta}}}\)</span>.</p>
<p>For the hypothesis testing, we:</p>
<ol style="list-style-type: decimal">
<li>Compute the standard error of <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(SE_{\beta_1}\)</span>:</li>
</ol>
<p><span class="math inline">\(SE_{\beta_1}=\frac {\sqrt{\frac{\sum{{Y_i - \hat{Y_i}}})^2}{{n - 2}}}}{\sqrt{\sum{(X_i - \bar{X})^2}}}\)</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Compute the <em>t</em>-statistic, in this case, we are comparing our observed value of <span class="math inline">\(\beta_1\)</span> to the expected value, if the null hypothesis is true. So, our expected value is <span class="math inline">\(\beta_1 = 0\)</span>. And we divide this difference by <span class="math inline">\(SE_{\beta_1}\)</span>.</li>
</ol>
<p><span class="math inline">\(t = \frac{\hat{\beta_1} - 0}{SE_{\beta_1}}\)</span>.</p>
<p><span class="math inline">\(t = \frac{\hat{\beta_1}}{SE_{\beta_1}}\)</span>.</p>
<p>This is our computed <em>t</em> value.</p>
<ol start="3" style="list-style-type: decimal">
<li><p>We calculate the critical value of <em>t</em>, which is derived using the degrees of freedom. For simple linear regression (one independent and one dependent variable), the degrees of freedom (df) is equal to, n - 2.</p></li>
<li><p>To determine the 95% CI of <span class="math inline">\(\beta_1\)</span>, we can rearrange the above equation:</p></li>
</ol>
<p><span class="math inline">\(t = \frac{\hat{\beta_1} - 0}{SE_{\beta_1}}\)</span>.</p>
<p><span class="math inline">\(t SE_{\beta_1} = \hat{\beta_1}\)</span>.</p>
<p><span class="math inline">\(\hat{\beta_1} = t_{\alpha, df} SE_{\beta_1}\)</span>.</p>
<p>If <span class="math inline">\(\alpha = 0.05\)</span>, then we would get the 95% confidence interval of <span class="math inline">\(\beta_1\)</span>.</p>
</div>
<div id="an-r-example" class="section level2">
<h2><span class="header-section-number">1.18</span> An R example</h2>
<pre class="r"><code>data(mtcars)
plot(mtcars$mpg ~ mtcars$hp)</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>model. &lt;- lm(mtcars$mpg ~ mtcars$hp)

summary(model.)$coef</code></pre>
<pre><code>##                Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) 30.09886054  1.6339210 18.421246 6.642736e-18
## mtcars$hp   -0.06822828  0.0101193 -6.742389 1.787835e-07</code></pre>
<p>The second column of the coefficients’ summary, reports <span class="math inline">\(SE_{\beta_1}\)</span> and <span class="math inline">\(SE_{\beta_0}\)</span>.</p>
<p>In the third column t value, we find the <em>t</em> statistics suitable for tests of the separate hypotheses:</p>
<p><span class="math inline">\(\beta_o = 0\)</span> and</p>
<p><span class="math inline">\(\beta_1 = 0\)</span>.</p>
<p>Furthermore, the output provides us with <em>p</em>-values corresponding to both tests against the two-sided hypothesis in the fourth column of the table.</p>
<p>Given these results:</p>
<p><span class="math inline">\(\beta_1 = -0.06822828\)</span></p>
<p><span class="math inline">\(SE_{\beta_1} = 0.0101193\)</span></p>
<p><span class="math inline">\(t = \frac{\hat{\beta_1} - 0}{SE_{\beta_1}}\)</span></p>
<p><span class="math inline">\(t = \frac{ -0.068}{0.0101}\)</span>.</p>
<p><span class="math inline">\(t = -6.742\)</span>.</p>
<p>95% CI of <span class="math inline">\(\beta_1\)</span>:</p>
<p><span class="math inline">\(t_{\alpha=0.05, df = (n - k -1)}\)</span></p>
<p><span class="math inline">\(t_{\alpha=0.05, df = (32 - 2 -1)}\)</span></p>
<p><span class="math inline">\(t_{\alpha=0.05, df = (29)}\)</span></p>
<p><span class="math inline">\(t_{\alpha=0.05, df = (29)} = -1.699\)</span></p>
<p>95% CI of <span class="math inline">\(\beta_1\)</span> = <span class="math inline">\(t_{\alpha=0.05, df = 29}SE_{\beta_1}\)</span> }</p>
<p><span class="math inline">\(\beta_1 = -0.068 \pm 0.017\)</span></p>
</div>
<div id="prediction-and-confidence-intervals" class="section level2">
<h2><span class="header-section-number">1.19</span> Prediction and confidence intervals</h2>
<p>Sometimes (often) we will want to use the model to predict values.</p>
<p>For example, suppose we fit a simple linear regression model using hours studied as a predictor variable and exam score as the response variable. Using this model, we might predict that a student who studies for 6 hours will receive an exam score of 91.</p>
<p>However, because there is uncertainty around this prediction, we might create a prediction interval that says there is a 95% chance that a student who studies for 6 hours will receive an exam score between 85 and 97.</p>
<p>This range of values is known as a 95% <em>prediction interval</em> and it’s often more useful to us than just knowing the predicted value. The predicted value <span class="math inline">\(\hat{Y_i}\)</span> is called a point and is useful. We would like to report the variability around this value..</p>
<p>Two type of intervals available:</p>
<p>1.) Confidence interval</p>
<p>A confidence interval captures the uncertainty around the mean predicted values.</p>
<p>2.) Prediction interval</p>
<p>The prediction interval predicts in what range a future individual observation will fall. A prediction interval will always be wider than a confidence interval for the same value.</p>
<p>Confidence interval:</p>
<p><span class="math inline">\(\hat{y} = s_yt_{(\alpha, df = n-2)}\sqrt{\frac{1}{n}+\frac{(X^*-\bar{X})^2}{(n-1)s^2_X}}\)</span></p>
<p>Here, <span class="math inline">\(s_y= \sqrt{\frac{\sum(y_i-\hat{y_i})^2}{n-2}}\)</span></p>
<p><span class="math inline">\(s_y\)</span> is called residual standard error in R regression output.</p>
<p>Prediction intervals are similar in their calculation</p>
<p><span class="math inline">\(\hat{y} = s_yt_{(\alpha, df = n-2)}\sqrt{1+\frac{1}{n}+\frac{(X^*-\bar{X})^2}{(n-1)s^2_X}}\)</span></p>
<p>Here, <span class="math inline">\(s_y= \sqrt{\frac{\sum(y_i-\hat{y_i})^2}{n-2}}\)</span></p>
<p>The formula is very similar, except the variability is higher since there is an added 1 in the formula.</p>
</div>
<div id="an-r-example---confidence-intervals" class="section level2">
<h2><span class="header-section-number">1.20</span> An R example - Confidence Intervals</h2>
<pre class="r"><code>data(mtcars)
mt &lt;- mtcars[order(mtcars$hp),]
plot(mt$mpg ~ mt$hp)
model. &lt;- lm(mt$mpg ~ mt$hp)

new_hp &lt;- data.frame(hp = mt$hp)
pred.vals &lt;- predict(model., newdata = new_hp, interval = &quot;confidence&quot;)

lines(cbind(new_hp, pred.vals)[,c(1,2)])
lines(cbind(new_hp, pred.vals)[,c(1,3)], col = &quot;red&quot;)
lines(cbind(new_hp, pred.vals)[,c(1,4)], col = &quot;red&quot;)</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
<div id="an-r-example---prediction-intervals" class="section level2">
<h2><span class="header-section-number">1.21</span> An R example - Prediction Intervals</h2>
<pre class="r"><code>data(mtcars)
mt &lt;- mtcars[order(mtcars$hp),]
plot(mt$mpg ~ mt$hp)
model. &lt;- lm(mt$mpg ~ mt$hp)

new_hp &lt;- data.frame(hp = mt$hp)
pred.vals &lt;- predict(model., newdata = new_hp, interval = &quot;prediction&quot;)

lines(cbind(new_hp, pred.vals)[,c(1,2)])
lines(cbind(new_hp, pred.vals)[,c(1,3)], col = &quot;red&quot;)
lines(cbind(new_hp, pred.vals)[,c(1,4)], col = &quot;red&quot;)</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
</div>
<div id="multiple-linear-regression" class="section level1">
<h1><span class="header-section-number">2</span> Multiple Linear Regression</h1>
<p>Model is fit by minimizing the sum of squared differences between the line and the actual data points - method of least squares.</p>
<p>We still use our base equation:</p>
<p><span class="math inline">\(outcome=model+error\)</span></p>
<p>But this time the model it is a bit more complicated.</p>
<p>When we add predictors, we add parameters (<span class="math inline">\(\beta\)</span> terms).</p>
<p>So each predictor variable has its own coefficient (parameter) and the outcome is predicted from a combination of all variables multiplied by their respective coefficients (<span class="math inline">\(\beta\)</span> terms).</p>
<div id="multiple-predictors" class="section level2">
<h2><span class="header-section-number">2.1</span> Multiple Predictors</h2>
<p><em>Y</em> is the outcome variable, <span class="math inline">\(\beta_1\)</span> is the coefficient of X1,<span class="math inline">\(\beta_n\)</span> is the coefficient of <span class="math inline">\(X_n\)</span>.</p>
<p>We seek to find combinations of <span class="math inline">\(\beta\)</span> values (parameters) that minimize the sum of squares error:</p>
<p><span class="math inline">\(outcome_i=model_i+error_i\)</span></p>
<p><span class="math inline">\(error_i = outcome_i - model_i\)</span></p>
<p>As you know, we quantify the error the model fitting using <span class="math inline">\(SS\)</span>.</p>
<p><span class="math inline">\(Y_i=(b_0 + b_1X_{1i}+b_2X_{2i}+\ldots+b_nX_{ni})+\varepsilon_i\)</span></p>
<p><span class="math inline">\(\varepsilon_i=Y_i-(b_0 + b_1X_{1i}+b_2X_{2i}+\ldots+b_nX_{ni})\)</span></p>
</div>
<div id="album-sales-model" class="section level2">
<h2><span class="header-section-number">2.2</span> Album Sales Model</h2>
<p>From our previous example above of record sales data, we know that advertising accounts for 33% of the variation in album sales.</p>
<p>Remember:</p>
<p><span class="math inline">\(R^2=\frac{SS_M}{SS_T}\)</span></p>
<p><span class="math inline">\(R^2=0.3313\)</span></p>
<p>Therefore a large proportion of variation remains unexplained.</p>
<p>Lets bring a new predictor variable into the mix to see if we can increase the amount of residual variation described by the model: How many times the song was played on the radio during the week prior to its release.</p>
</div>
<div id="multiple-predictors-model" class="section level2">
<h2><span class="header-section-number">2.3</span> Multiple Predictors Model</h2>
<p>We will incorporate a new “airplay” variable.</p>
<p>So we have a model with three parameters and two slope coefficients. Because there are two predictors, so we can view the model in two dimensions:</p>
<p><span class="math inline">\(E(Album \:Sales_i)=\beta_0+\beta_1X_{advertising \: budget_i}+\beta_2X_{airplay_i}\)</span></p>
</div>
<div id="regression-plane" class="section level2">
<h2><span class="header-section-number">2.4</span> Regression “Plane”</h2>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="multiple-linear-regression-1" class="section level2">
<h2><span class="header-section-number">2.5</span> Multiple Linear Regression</h2>
<table>
<thead>
<tr class="header">
<th>Cities</th>
<th>Y</th>
<th>X<sub>1</sub></th>
<th>X<sub>2</sub></th>
<th>X<sub>3</sub></th>
<th>X<sub>4</sub></th>
<th>X<sub>5</sub></th>
<th>X<sub>6</sub></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pheonix</td>
<td>10</td>
<td>70.3</td>
<td>213</td>
<td>582</td>
<td>6.0</td>
<td>7.05</td>
<td>36</td>
</tr>
<tr class="even">
<td>Little Rock</td>
<td>13</td>
<td>61.0</td>
<td>91</td>
<td>132</td>
<td>8.2</td>
<td>48.52</td>
<td>100</td>
</tr>
<tr class="odd">
<td>San Francisco</td>
<td>12</td>
<td>56.7</td>
<td>453</td>
<td>716</td>
<td>8.7</td>
<td>20.66</td>
<td>67</td>
</tr>
<tr class="even">
<td>Denver</td>
<td>17</td>
<td>51.9</td>
<td>454</td>
<td>515</td>
<td>9.0</td>
<td>12.95</td>
<td>86</td>
</tr>
<tr class="odd">
<td>Hartford</td>
<td>56</td>
<td>49.1</td>
<td>412</td>
<td>158</td>
<td>9.0</td>
<td>43.37</td>
<td>127</td>
</tr>
<tr class="even">
<td>Wilmington</td>
<td>36</td>
<td>54.0</td>
<td>80</td>
<td>80</td>
<td>9.0</td>
<td>40.25</td>
<td>114</td>
</tr>
<tr class="odd">
<td>Washington</td>
<td>29</td>
<td>57.3</td>
<td>434</td>
<td>757</td>
<td>9.3</td>
<td>38.89</td>
<td>111</td>
</tr>
<tr class="even">
<td>Jacksonville</td>
<td>14</td>
<td>68.4</td>
<td>136</td>
<td>529</td>
<td>8.8</td>
<td>54.57</td>
<td>116</td>
</tr>
<tr class="odd">
<td>Miami</td>
<td>10</td>
<td>75.5</td>
<td>207</td>
<td>335</td>
<td>9.0</td>
<td>59.80</td>
<td>128</td>
</tr>
<tr class="even">
<td>Atlanta</td>
<td>24</td>
<td>61.5</td>
<td>368</td>
<td>497</td>
<td>9.1</td>
<td>48.34</td>
<td>115</td>
</tr>
<tr class="odd">
<td>Chicago</td>
<td>110</td>
<td>50.6</td>
<td>3344</td>
<td>3369</td>
<td>10.4</td>
<td>34.44</td>
<td>122</td>
</tr>
<tr class="even">
<td>Indianapolis</td>
<td>28</td>
<td>52.3</td>
<td>361</td>
<td>746</td>
<td>9.7</td>
<td>38.74</td>
<td>121</td>
</tr>
<tr class="odd">
<td>Des Moines</td>
<td>17</td>
<td>49.0</td>
<td>104</td>
<td>201</td>
<td>11.2</td>
<td>30.85</td>
<td>103</td>
</tr>
<tr class="even">
<td>Wichita</td>
<td>8</td>
<td>56.6</td>
<td>125</td>
<td>277</td>
<td>12.7</td>
<td>30.58</td>
<td>82</td>
</tr>
<tr class="odd">
<td>Louisville</td>
<td>30</td>
<td>55.6</td>
<td>291</td>
<td>593</td>
<td>8.3</td>
<td>43.11</td>
<td>123</td>
</tr>
<tr class="even">
<td>New Orleans</td>
<td>9</td>
<td>68.3</td>
<td>204</td>
<td>361</td>
<td>8.4</td>
<td>56.77</td>
<td>113</td>
</tr>
<tr class="odd">
<td>Baltimore</td>
<td>47</td>
<td>55.0</td>
<td>625</td>
<td>905</td>
<td>9.6</td>
<td>41.31</td>
<td>111</td>
</tr>
<tr class="even">
<td>Detroit</td>
<td>35</td>
<td>49.9</td>
<td>1064</td>
<td>1513</td>
<td>10.1</td>
<td>30.96</td>
<td>129</td>
</tr>
<tr class="odd">
<td>Minneapolis- St. Paul</td>
<td>29</td>
<td>43.5</td>
<td>699</td>
<td>744</td>
<td>10.6</td>
<td>25.94</td>
<td>137</td>
</tr>
<tr class="even">
<td>Kansas City</td>
<td>14</td>
<td>54.5</td>
<td>381</td>
<td>507</td>
<td>10.0</td>
<td>37.00</td>
<td>99</td>
</tr>
<tr class="odd">
<td>St. Louis</td>
<td>56</td>
<td>55.9</td>
<td>775</td>
<td>622</td>
<td>9.5</td>
<td>35.89</td>
<td>105</td>
</tr>
<tr class="even">
<td>Omaha</td>
<td>14</td>
<td>51.5</td>
<td>181</td>
<td>347</td>
<td>10.9</td>
<td>30.18</td>
<td>98</td>
</tr>
<tr class="odd">
<td>Alburquerque</td>
<td>11</td>
<td>56.8</td>
<td>46</td>
<td>244</td>
<td>8.9</td>
<td>7.77</td>
<td>58</td>
</tr>
<tr class="even">
<td>Albany</td>
<td>46</td>
<td>47.6</td>
<td>44</td>
<td>116</td>
<td>8.8</td>
<td>33.36</td>
<td>135</td>
</tr>
<tr class="odd">
<td>Buffalo</td>
<td>11</td>
<td>47.1</td>
<td>391</td>
<td>463</td>
<td>12.4</td>
<td>36.11</td>
<td>166</td>
</tr>
<tr class="even">
<td>Cincinnati</td>
<td>23</td>
<td>54.0</td>
<td>462</td>
<td>453</td>
<td>7.1</td>
<td>39.04</td>
<td>132</td>
</tr>
</tbody>
</table>
<p><em>Table of air pollution in 41 U.S. cities associatied with six environmental variables</em></p>
</div>
<div id="model-interpretation" class="section level2">
<h2><span class="header-section-number">2.6</span> Model Interpretation</h2>
<p>We regress SO<sub>2</sub> content in the air on average temperature X<sub>1</sub> and the number of manufacturing enterprises, X<sub>2</sub></p>
<p><span class="math inline">\(\hat{Y} = 77.231 + 1.0480X_1 + 0.02431X_2\)</span></p>
<p>A one unit change in <span class="math inline">\(X_2\)</span> results in a 0.02431 increase in <em>Y</em>.</p>
<p>A one unit change in <span class="math inline">\(X_1\)</span> results in a 1.048 increase in <em>Y</em>.</p>
</div>
<div id="test-of-null-hypothesis" class="section level2">
<h2><span class="header-section-number">2.7</span> Test of Null Hypothesis</h2>
<p>We can analyze the null hypothesis that all of the regression coefficients are equal to zero using an ANOVA analysis. This approach is analogous to that used in simple linear regression.</p>
</div>
<div id="significance-testing" class="section level2">
<h2><span class="header-section-number">2.8</span> Significance Testing</h2>
<p>In general, a significant <em>F</em> value will be associated with the rejection of the null hypothesis for some regression coefficients.</p>
</div>
<div id="multicollinearity" class="section level2">
<h2><span class="header-section-number">2.9</span> Multicollinearity</h2>
<p>Sometimes it is possible to have a significant <em>F</em> without significant regression coefficients. Multicollinearity occurs when there is multicollinearity among variables.</p>
<ul>
<li><p>This happens when two variables are highly correlated.</p></li>
<li><p>Result in untrustworthy coefficients - serves to increase the variance of the estimate of the <span class="math inline">\(\beta\)</span> values.</p></li>
<li><p>Example: inclusion of one predictor results in R2 = 0.80.</p></li>
<li><p>When you add a highly correlated variable, the variance it accounts for is already described by the first variable - it does not account for unique variance.</p></li>
<li><p>So we only get a slight increase in our <em>R</em> value.</p></li>
<li><p>We can deal with this by evaluating the variables prior to inclusion into the model.</p></li>
</ul>
</div>
<div id="determination-of-predictors-to-include" class="section level2">
<h2><span class="header-section-number">2.10</span> Determination of Predictors to Include?</h2>
<p>One of the most widespread ways is to use “stepwise” methods, you specify a direction either forward or backward.</p>
<p>Forward selection:</p>
<ul>
<li>Initial model with only the constant b0 is made</li>
<li>Add single predictor that best predicts the outcome by selecting the one with the greatest correlation with the outcome</li>
<li>If fit is improved, then the predictor is retained</li>
<li>Repeat</li>
</ul>
<p>Backward selection:</p>
<ul>
<li>As above but remove coefficients one at a time.</li>
</ul>
</div>
<div id="model-design-considerations-1" class="section level2">
<h2><span class="header-section-number">2.11</span> Model Design Considerations 1</h2>
<ul>
<li><p>Predictor variables must be either continuous or categorical.</p></li>
<li><p>Predictors should have non-zero variance.</p></li>
<li><p>Predictors should not be highly correlated (avoid multicollinearity).</p></li>
<li><p>It is desirable to employ a regression that is parsimonious - as few as necessary but as many as needed.</p></li>
</ul>
</div>
</div>
<div id="comparing-two-means-using-t-tests" class="section level1">
<h1><span class="header-section-number">3</span> Comparing Two Means using <em>t</em>-tests</h1>
<p>A common situation is the comparison of the means of two populations.</p>
<p>An example of a <em>t</em>-test is to evaluate the mean blood clotting times between populations that were given two drugs.</p>
<ul>
<li><span class="math inline">\(H_0: \mu_B = \mu_G\)</span>, where <span class="math inline">\(\mu\)</span> is the mean blood clotting time (in minutes)</li>
</ul>
<p>If the samples came from two normally distributed populations and the variances of the populations are equal ,we can use a two sample <em>t</em>-test. These conform to the assumptions of parametric statistics.</p>
<ul>
<li><p>Two samples of data are collected and the sample means calculated.</p></li>
<li><p>The calculated means might differ by either a little or a lot.</p></li>
</ul>
<div id="small-differences-in-mean-samples-values" class="section level2">
<h2><span class="header-section-number">3.1</span> Small differences in mean samples values</h2>
<p>We expect their means to be equal or very close. In this case, it is possible (even likely) for the population means to differ by chance alone (due to sampling error). We wwould expect that large differences in the mean values would occur very infrequently.</p>
<p><span class="math inline">\(H_0: \mu_B = \mu_G\)</span></p>
<p>Alternatively, we can pose this as the difference in the mean:</p>
<p><span class="math inline">\(H_0: \mu_B - \mu_G = 0\)</span>.</p>
<ul>
<li><p>We are interested in understanding the magnitude of difference between the sample means.</p></li>
<li><p>We use the standard error as a gauge of the variability between sample means.</p></li>
</ul>
</div>
<div id="large-differences-in-mean-samples-values" class="section level2">
<h2><span class="header-section-number">3.2</span> Large differences in mean samples values</h2>
<p>If the difference between the samples we have collected is large, then we can infer one of two things:</p>
<p>1.) There is no effect of the two blood clotting medicine and by chance we calculated two sample means that are atypical of the population from which they came.</p>
<p>2.) The two samples come from different populations (populations with different mean values). In this scenario, the difference between samples represents a genuine difference between the samples (and we falsify the null hypothesis).</p>
<p>So, this is the null model we are testing; did the samples come from the same population or did the samples come from the different populations?</p>
<p>If the observed difference between the sample means is large: The more confident we become that the second explanation is correct (i.e. that the null hypothesis should be rejected).</p>
</div>
<div id="example" class="section level2">
<h2><span class="header-section-number">3.3</span> Example</h2>
<ul>
<li><p>Is arachnophobia (fear of spiders) specific to real spiders or is a picture enough?</p></li>
<li><p>24 arachnophobic individuals</p></li>
</ul>
<p>Experimental Manipulation:</p>
<ul>
<li><p>n = 12 randomly chosen participants were exposed to a real spider.</p></li>
<li><p>n = 12 randomly chosen participants were exposed to a picture of the same spider.</p></li>
<li><p>We monitor the anxiety produced.</p></li>
</ul>
</div>
<div id="we-will-evaluate-these-data-using-a-linear-model" class="section level2">
<h2><span class="header-section-number">3.4</span> We will evaluate these data using a linear model</h2>
<p>Consider an experiment where ‘Groups’ were exposed to a “Picture of a Spider” and an “Actual Spider”</p>
<p>The response variable is the level of Anxiety (A)</p>
<p><span class="math inline">\(\hat{A_i}=b_0+b_1G_i\)</span></p>
<p>The independent variable <em>G</em> has only two values “Group 1” and “Group 2” ie. The “real” and “picture” groups.</p>
<pre><code>##          Group  Anxiety G
## 1      Picture 20.67124 0
## 2      Picture 36.79956 0
## 3      Picture 38.36280 0
## 4      Picture 26.76544 0
## 5      Picture 36.46704 0
## 6      Picture 15.36294 0
## 7      Picture 20.63903 0
## 8      Picture 23.93972 0
## 9      Picture 40.35177 0
## 10     Picture 41.79260 0
## 11     Picture 31.16043 0
## 12     Picture 28.42174 0
## 13 Real Spider 23.68506 1
## 14 Real Spider 59.23398 1
## 15 Real Spider 35.84786 1
## 16 Real Spider 47.14871 1
## 17 Real Spider 44.51467 1
## 18 Real Spider 52.42887 1
## 19 Real Spider 61.94535 1
## 20 Real Spider 52.43209 1
## 21 Real Spider 39.05075 1
## 22 Real Spider 57.72527 1
## 23 Real Spider 48.60876 1
## 24 Real Spider 41.13388 1</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
</div>
<div id="picture-group" class="section level2">
<h2><span class="header-section-number">3.5</span> Picture Group</h2>
<p>We can code the variable, <em>G</em>, as a ‘dummy’ variable. It will take on the values one or zero. We can assign one group to have a value of zero, and one group to have a value of one. In the case of the ‘picture’ group, we will assign a value of <em>G</em> to be zero.</p>
<p><span class="math inline">\(G_{picture}=0\)</span></p>
<p><span class="math inline">\(\hat{A_i}=b_0+b_1G_i\)</span></p>
<p>The expected anxiety of group “picture” is the mean of anxiety of group “picture”.</p>
<p><span class="math inline">\(\bar{A}_{Picture}=b_0+b_1G_{picture}\)</span></p>
<p><span class="math inline">\(\bar{A}_{Picture}=b_0+b_1\times0\)</span></p>
<p><span class="math inline">\(\bar{A}_{Picture}=b_0\)</span></p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
<div id="real-spider-group" class="section level2">
<h2><span class="header-section-number">3.6</span> Real Spider Group</h2>
<p>Again, we can code the variable, <em>G</em>, as a ‘dummy’ variable. It can take on the values one or zero.</p>
<p>We have assigned a value of <em>G</em> to be zero for the “picture” group. So, for the “real” group, we will assign the dummy variable <em>G</em> to equal one.</p>
<p><span class="math inline">\(G_{real}=1\)</span></p>
<p><span class="math inline">\(\hat{A_{G=1}}=b_0+b_1G_i\)</span></p>
<p><span class="math inline">\(\hat{A_i}=30.06+b_1\times1\)</span></p>
<p><span class="math inline">\(\hat{A_i}=30.06+b_1\)</span></p>
<p><span class="math inline">\(b_1 = \hat{A_i}-30.06\)</span></p>
<p><span class="math inline">\(b_1\)</span> = Difference between means</p>
<p><span class="math inline">\(b_1=\bar{A}_{Real}-\bar{A}_{Picture}\)</span></p>
<p>Our task is to understand if this <span class="math inline">\(\beta_1\)</span> value is significantly different from zero.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="output-from-a-regression" class="section level2">
<h2><span class="header-section-number">3.7</span> Output from a Regression</h2>
<p>Let’s see how this is analyzed in the linear regression approach using R:</p>
<pre><code>## 
## Call:
## lm(formula = df.$Anxiety ~ df.$Group)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -23.2945  -6.5733   0.6342   7.1292  14.9657 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            30.061      2.864  10.496 4.97e-10 ***
## df.$GroupReal Spider   16.918      4.050   4.177 0.000392 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.921 on 22 degrees of freedom
## Multiple R-squared:  0.4423, Adjusted R-squared:  0.4169 
## F-statistic: 17.45 on 1 and 22 DF,  p-value: 0.0003915</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: df.$Anxiety
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## df.$Group  1 1717.4 1717.40  17.448 0.0003915 ***
## Residuals 22 2165.5   98.43                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="the-independent-t-test" class="section level2">
<h2><span class="header-section-number">3.8</span> The Independent <em>t-test</em></h2>
<p>I am using the variable <em>Y</em> for the observations - this is a departure from Zar’s presentation but the mechanics are identical.</p>
<p><span class="math inline">\(t=\frac{\bar{Y}_1-\bar{Y}_2}{\sqrt{\frac{S^2_p}{n_1}+\frac{S^2_p}{n_2}}}\)</span></p>
<ul>
<li><p>The numerator is the difference between sample means.</p></li>
<li><p>The denominator is the standard error of the difference between the sample means. This quantity is a measure of the variability of the data within the two samples.</p></li>
</ul>
<p><span class="math inline">\(S^2_p=\frac{(n_1-1)S^2_1+(n_2-1)S^2_2}{n_1+n_2-2}\)</span></p>
<p><span class="math inline">\(S^2_p=\frac{SS_1+SS_2}{v_1+v_2}\)</span></p>
<p>Here v<sub>1</sub> and v<sub>2</sub> are the degrees of freedom, v<sub>1</sub> = n<sub>1</sub> - 1 and v<sub>2</sub> = n<sub>2</sub> -1</p>
<p>The test value is compared to the critical value at a given <span class="math inline">\(\alpha\)</span></p>
<p><span class="math inline">\(t_{\alpha,2,df}\)</span></p>
<ul>
<li>Need to set <span class="math inline">\(\alpha\)</span> value.</li>
<li>One or two-tailed test?</li>
<li>v<sub>1</sub> = n<sub>1</sub> - 1 and v<sub>2</sub> = n<sub>2</sub> - 1</li>
</ul>
</div>
<div id="lets-use-the-data-from-zar-as-a-worked-example." class="section level2">
<h2><span class="header-section-number">3.9</span> Lets use the data from Zar as a worked example.</h2>
<p><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span> <span class="math inline">\(H_A: \mu_1\ne\mu_2\)</span></p>
<p><span class="math inline">\(H_0: \mu_1 - \mu_2 = 0\)</span> <span class="math inline">\(H_A: \mu_1-\mu_2\ne0\)</span></p>
<table>
<thead>
<tr class="header">
<th align="center">Given drug B</th>
<th align="center">Given drug G</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">8.8</td>
<td align="center">9.9</td>
</tr>
<tr class="even">
<td align="center">8.4</td>
<td align="center">9.0</td>
</tr>
<tr class="odd">
<td align="center">7.9</td>
<td align="center">11.1</td>
</tr>
<tr class="even">
<td align="center">8.7</td>
<td align="center">9.6</td>
</tr>
<tr class="odd">
<td align="center">9.1</td>
<td align="center">8.7</td>
</tr>
<tr class="even">
<td align="center">9.6</td>
<td align="center">10.4</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">9.5</td>
</tr>
<tr class="even">
<td align="center">——</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(n_1=6\)</span></td>
<td align="center"><span class="math inline">\(n_2=7\)</span></td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\nu_1=5\)</span></td>
<td align="center"><span class="math inline">\(\nu_2=6\)</span></td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(\bar{Y}_1=\)</span> 8.75 min</td>
<td align="center"><span class="math inline">\(\bar{Y}_2=\)</span> 9.74 min</td>
</tr>
<tr class="even">
<td align="center">SS<sub>1</sub> = 1.6950 min<sup>2</sup></td>
<td align="center"> SS<sub>2</sub> = 4.0171 min<sup>2</sup></td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(S^2_p=\frac{SS_1+SS_2}{v_1+v_2}=\frac{1.6950+4.0171}{5+6}=\frac{5.7121}{11}=0.5193 \: \mbox{min}^2\)</span></p>
<p><span class="math inline">\(s_{\bar{Y_1}-\bar{Y}_2}=\sqrt{\frac{S^2_p}{n_1}+\frac{S^2_p}{n_2}}=\sqrt{\frac{0.5193}{6}+\frac{0.5193}{7}}=\sqrt{0.0866+0.0742}\)</span></p>
<p><span class="math inline">\(=\sqrt{0.1608}=0.40\mbox{min}\)</span></p>
<p><span class="math inline">\(t=\frac{\bar{Y}_1-\bar{Y}_2}{s_{\bar{Y}_1-\bar{Y}_2}}\)</span></p>
</div>
<div id="determine-test-value" class="section level2">
<h2><span class="header-section-number">3.10</span> Determine test value</h2>
<p><span class="math inline">\(t=\frac{\bar{Y}_1-\bar{Y}_2}{s_{\bar{Y}_1-\bar{Y}_2}}=\frac{8.75-9.74}{0.40}=\frac{-0.99}{0.40}=-2.475\)</span></p>
<p><span class="math inline">\(|t|=|\frac{\bar{Y}_1-\bar{Y}_2}{s_{\bar{Y}_1-\bar{Y}_2}}|=2.475\)</span></p>
</div>
<div id="determine-critical-value" class="section level2">
<h2><span class="header-section-number">3.11</span> Determine critical value</h2>
<p><span class="math inline">\(t_{0.05(2),v}=t_{0.05(2),11}=2.201\)</span></p>
<p>Therefore, reject H<sub>0</sub></p>
<p><span class="math inline">\(P(|t|\ge2.475)&lt;0.05\)</span> <span class="math inline">\(\: \:\)</span> <span class="math inline">\(P=0.031\)</span></p>
</div>
<div id="when-assumptions-are-broken" class="section level2">
<h2><span class="header-section-number">3.12</span> When Assumptions are Broken</h2>
<ul>
<li>Non-parameteric <em>t</em>-test Mann-Whitney “U” Test</li>
</ul>
<p>+Do not require estimation of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>.</p>
<p>+No assumptions about distributions.</p>
<ul>
<li><p>Convert data to RANKS of data.</p></li>
<li><p>Two sample rank test</p></li>
<li><p>Rank from highest to lowest, the greatest value in either group is given a one, second given a two..</p></li>
</ul>
<p><span class="math inline">\(U=n_1n_2+\frac{n_1(n_1+1)}{2}-R_1\)</span></p>
<ul>
<li>n<sub>1</sub> and n<sub>2</sub> are the number of observation sin samples 1 and 2.</li>
<li>R<sub>1</sub> is the sum of the ranks in sample 1</li>
</ul>
<p>H<sub>0</sub>: Male and female students are the same height. H<sub>A</sub>: Male and female students are not the same height.</p>
<p><span class="math inline">\(\alpha=0.05\)</span></p>
<table>
<colgroup>
<col width="25%" />
<col width="25%" />
<col width="25%" />
<col width="25%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Height of males</th>
<th align="center">Height of females</th>
<th align="center">Ranks of male heights</th>
<th align="center">Ranks of female heights</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">193 cm</td>
<td align="center">178 cm</td>
<td align="center">1</td>
<td align="center">6</td>
</tr>
<tr class="even">
<td align="center">188</td>
<td align="center">173</td>
<td align="center">2</td>
<td align="center">8</td>
</tr>
<tr class="odd">
<td align="center">185</td>
<td align="center">168</td>
<td align="center">3</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td align="center">183</td>
<td align="center">165</td>
<td align="center">4</td>
<td align="center">11</td>
</tr>
<tr class="odd">
<td align="center">180</td>
<td align="center">163</td>
<td align="center">5</td>
<td align="center">12</td>
</tr>
<tr class="even">
<td align="center">175</td>
<td align="center"></td>
<td align="center">7</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">170</td>
<td align="center"></td>
<td align="center">9</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">—</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center"><span class="math inline">\(n_1=7\)</span></td>
<td align="center"><span class="math inline">\(n_2=5\)</span></td>
<td align="center"><span class="math inline">\(R_1=31\)</span></td>
<td align="center"><span class="math inline">\(R_2=47\)</span></td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(U=n_1n_2+\frac{n_1(n_1+1)}{2}-R_1\)</span></p>
<p><span class="math inline">\((7)(5)+\frac{(7)(8)}{2}-31\)</span></p>
<p><span class="math inline">\(35+28-31\)</span></p>
<p><span class="math inline">\(32\)</span></p>
<p><span class="math inline">\(U^1=n_1n_2-U\)</span></p>
<p><span class="math inline">\((7)(5)-32\)</span></p>
<p><span class="math inline">\(U_{0.05(2),5,7}=30\)</span></p>
<p>Because 32&gt;30, H<sub>0</sub> is rejected.</p>
<p>Therefore, we conclude that height is different for male and female students.</p>
</div>
</div>
<div id="analysis-of-variance-anova" class="section level1">
<h1><span class="header-section-number">4</span> Analysis of Variance (ANOVA)</h1>
<p>In this module we will understand the basic principles of ANOVA. We will be analyzing one-way ANOVA, also called ‘one-factor’ ANOVA or ‘single factor Analysis of Variance’. We will be analyzing the impact to the mean value among <em>k</em> groups, where <span class="math inline">\(k &gt;2\)</span>. ANOVA is a parametric test.</p>
<p>We will stick with Zar’s terminology (p 178, 4th edition).</p>
<div id="when-and-why-to-use-anova" class="section level2">
<h2><span class="header-section-number">4.1</span> When and why to use ANOVA</h2>
<p>When we want to compare means we can use a <em>t</em>-test but this test has limitations, we can only test the equality of two mean values. Often we would like to compare means from three or more groups.</p>
<p>The ANOVA is an extension of regression (and hence is a general linear model).</p>
<div id="why-not-use-lots-of-t-tests" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Why Not Use Lots of <em>t</em>-tests?</h3>
<ul>
<li>Inflates the Type I error rate</li>
<li><span class="math inline">\(1 - (1- \alpha)^n\)</span></li>
</ul>
</div>
</div>
<div id="what-does-anova-tell-us" class="section level2">
<h2><span class="header-section-number">4.2</span> What Does ANOVA Tell Us?</h2>
<p>Null hypothesis:</p>
<ul>
<li>Like a <em>t</em>-test, <em>one way</em> ANOVA tests the null hypothesis that the means are the same among groups.</li>
</ul>
<p>ANOVA is an <em>omnibus</em> test:</p>
<ul>
<li>It test for an overall test for evaluating the equality of means among groups.</li>
<li>It tells us that the group means are different.</li>
<li>It doesn’t tell us which mean(s) differ.</li>
</ul>
</div>
<div id="anova-as-regression" class="section level2">
<h2><span class="header-section-number">4.3</span> ANOVA as Regression</h2>
<p>Let us assume that we test three different medicine levels and want to see if it impacts (results in contrast, i.e. significant differences) the illness level in pigs.</p>
<p>We are going to test the effect of the three groups (<em>k</em> = 3), in this case medicine type. The three groups are ‘placebo’, ‘high’, and ‘low’.</p>
<p>The analysis is termed a one-factor test or one-way ANOVA (only a single thing, the medicine, is different).</p>
<p>Pigs are assigned, at random, to each of the three groups. These are the replicates of each group.</p>
<p><span class="math inline">\(\mbox{illness}_i=b_0+b_1\mbox{low}_i+b_2\mbox{high}_i+\varepsilon_i\)</span></p>
<p>Here <span class="math inline">\(high\)</span> and <span class="math inline">\(low\)</span> are dummy variables, just like <em>G</em> in the <em>t</em>-test.</p>
<table>
<thead>
<tr class="header">
<th align="center">Group</th>
<th align="center">Dummy variable 1 (High)</th>
<th align="center">Dummy variable 2 (Low)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Placebo</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">Low dose medicine</td>
<td align="center">0</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">High dose medicine</td>
<td align="center">1</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
</div>
<div id="placebo-group" class="section level2">
<h2><span class="header-section-number">4.4</span> Placebo Group</h2>
<p><span class="math inline">\(\mbox{illness}_i=b_0+b_1\mbox{low}_i+b_2\mbox{high}_i+\varepsilon_i\)</span></p>
<p><span class="math inline">\(\mbox{illness}_i=b_0+(b_1\times 0)+(b_2\times 0)\)</span></p>
<p><span class="math inline">\(\mbox{illness}_i=b_0\)</span></p>
<p><span class="math inline">\(\bar{Y}_{placebo}=b_0\)</span></p>
</div>
<div id="low-dose-group" class="section level2">
<h2><span class="header-section-number">4.5</span> Low Dose Group</h2>
<p><span class="math inline">\(\mbox{illness}_i=b_0+b_1\mbox{low}_i+b_2\mbox{high}_i+\varepsilon_i\)</span></p>
<p><span class="math inline">\(\mbox{illness}_i=b_0+(b_1\times 1)+(b_2\times 0)\)</span></p>
<p><span class="math inline">\(\mbox{illness}_i=b_0+b_1\)</span></p>
<p><span class="math inline">\(\bar{Y}_{low}=\bar{Y}_{placebo}+b_1\)</span></p>
<p><span class="math inline">\(b_1=\bar{Y}_{low}-\bar{Y}_{placebo}\)</span></p>
</div>
<div id="high-dose-group" class="section level2">
<h2><span class="header-section-number">4.6</span> High Dose Group</h2>
<p><span class="math inline">\(\mbox{illness}_i=b_0+b_1\mbox{low}_i+b_2\mbox{high}_i+\varepsilon_i\)</span></p>
<p><span class="math inline">\(\mbox{illness}_i=b_0+(b_1\times 0)+(b_2\times 1)\)</span></p>
<p><span class="math inline">\(\mbox{illness}_i=b_0+b_2\)</span></p>
<p><span class="math inline">\(\bar{Y}_{high}= \bar{Y}_{placebo}+b_2\)</span></p>
<p><span class="math inline">\(b_2=\bar{Y}_{high}-\bar{Y}_{placebo}\)</span></p>
</div>
<div id="output-from-regression" class="section level2">
<h2><span class="header-section-number">4.7</span> Output from Regression</h2>
<table>
<thead>
<tr class="header">
<th align="center">Coefficients:</th>
<th align="center">Estimate</th>
<th align="center">Std. Error</th>
<th align="center">t value</th>
<th align="center">Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">(intercept)</td>
<td align="center">2.2000</td>
<td align="center">0.6272</td>
<td align="center">3.508</td>
<td align="center">0.00432 **</td>
</tr>
<tr class="even">
<td align="center">dummy 1</td>
<td align="center">2.8000</td>
<td align="center">0.8869</td>
<td align="center">3.157</td>
<td align="center">0.00827 **</td>
</tr>
<tr class="odd">
<td align="center">dummy 2</td>
<td align="center">1.0000</td>
<td align="center">0.8869</td>
<td align="center">1.127</td>
<td align="center">0.28158</td>
</tr>
</tbody>
</table>
<p>Signif. Codes:  0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05’.’ 0.1 ’’ 1</p>
<ul>
<li>residual standard error:  1.402 on 12 degrees of freedom.</li>
<li>Multiple R-squared:  0.4604, Adjusted R-squared:  0.3704</li>
<li><em>F</em>-statistic:  5.119 on 2 and 12 df, p-value:  0.02469</li>
</ul>
</div>
<div id="theory-of-anova" class="section level2">
<h2><span class="header-section-number">4.8</span> Theory of ANOVA</h2>
<p>We use SS components:</p>
<p>First, we calculate how much variability there is between scores</p>
<ul>
<li>Total sum of squares (SS<sub>T</sub>).</li>
</ul>
<p>We then calculate how much of this variability can be explained by the model we fit to the data</p>
<ul>
<li><p>How much variability is due to the experimental manipulation? This is evaluated using the model sum of squares (SS<sub>M</sub>)</p></li>
<li><p>How much variability is due to individual differences in performance, residual sum of squares (SS<sub>R</sub>).</p></li>
<li><p>We compare the amount of variability explained by the model (experiment), to the error in the model (individual differences)</p></li>
<li><p>This ratio is called the <em>F</em>-ratio.</p></li>
</ul>
<p>If the model explains a lot more variability than it can’t explain, then the experimental manipulation has had a significant effect on the outcome.</p>
</div>
<div id="anova-worked-example" class="section level2">
<h2><span class="header-section-number">4.9</span> ANOVA Worked Example</h2>
<p>Testing the effects of medicine on illness using three groups:</p>
<ul>
<li>Placebo (sugar pill)</li>
<li>Low dose medicine</li>
<li>High dose medicine</li>
</ul>
<p>The outcome/dependent variable (DV) was an objective measure of illness.</p>
</div>
<div id="the-data" class="section level2">
<h2><span class="header-section-number">4.10</span> The Data</h2>
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Placebo</th>
<th align="center">Low Dose</th>
<th align="center">High Dose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"></td>
<td align="center">3</td>
<td align="center">5</td>
<td align="center">7</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">2</td>
<td align="center">2</td>
<td align="center">4</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">1</td>
<td align="center">4</td>
<td align="center">5</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">1</td>
<td align="center">2</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">4</td>
<td align="center">3</td>
<td align="center">6</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\bar{Y}\)</span></td>
<td align="center">2.20</td>
<td align="center">3.20</td>
<td align="center">5.00</td>
</tr>
<tr class="odd">
<td align="center"><em>s</em></td>
<td align="center">1.30</td>
<td align="center">1.30</td>
<td align="center">1.58</td>
</tr>
<tr class="even">
<td align="center"><em>s</em><sup>2</sup></td>
<td align="center">1.70</td>
<td align="center">1.70</td>
<td align="center">2.50</td>
</tr>
</tbody>
</table>
<p>Grand Mean = 3.467, Grand <em>s</em> = 1.767, Grand <em>s</em><sup>2</sup> = 3.124</p>
</div>
<div id="step-1-calculate-sst" class="section level2">
<h2><span class="header-section-number">4.11</span> Step 1: Calculate SS<sub>T</sub></h2>
<p><em>SS<sub>T</sub> uses the differences between the observed data and the mean value of Y. Where the mean is the grand mean</em></p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Placebo</th>
<th align="center">Low Dose</th>
<th align="center">High Dose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"></td>
<td align="center">3</td>
<td align="center">5</td>
<td align="center">7</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">2</td>
<td align="center">2</td>
<td align="center">4</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">1</td>
<td align="center">4</td>
<td align="center">5</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">1</td>
<td align="center">2</td>
<td align="center">3</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">4</td>
<td align="center">3</td>
<td align="center">6</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(\bar{Y}\)</span></td>
<td align="center">2.20</td>
<td align="center">3.20</td>
<td align="center">5.00</td>
</tr>
<tr class="odd">
<td align="center"><em>s</em></td>
<td align="center">1.30</td>
<td align="center">1.30</td>
<td align="center">1.58</td>
</tr>
<tr class="even">
<td align="center"><em>s</em><sup>2</sup></td>
<td align="center">1.70</td>
<td align="center">1.70</td>
<td align="center">2.50</td>
</tr>
</tbody>
</table>
<p>Grand Mean = 3.467, Grand <em>s</em> = 1.767, Grand <em>s</em><sup>2</sup> = 3.124</p>
<p>SS<sub>T</sub> = sum((observed - Grand mean)<sup>2</sup>) <span class="math inline">\(SS_T=\sum(obs_i - \bar{X}_{grand})\)</span></p>
</div>
<div id="degrees-of-freedom" class="section level2">
<h2><span class="header-section-number">4.12</span> Degrees of Freedom</h2>
<p>Degrees of freedom (df) are the number of values that are free to vary.</p>
<p>In general, the df are one less than the number of values used to calculate the SS.</p>
<p>df<sub>Total</sub> = N - 1</p>
</div>
<div id="model-sum-of-squares-ssm" class="section level2">
<h2><span class="header-section-number">4.13</span> Model Sum of Squares (SS<sub>M</sub>)</h2>
<p>Difference between the model estimate and the mean (or “Grand Mean”)</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
<div id="step-2-calculate-ssm" class="section level2">
<h2><span class="header-section-number">4.14</span> Step 2: Calculate SS<sub>M</sub></h2>
<p><span class="math inline">\(SS_M=\sum n_i(\bar{x}_i - \bar{x}_{grand})^2\)</span></p>
<p><span class="math inline">\(SS_M=5(2.2-3.467)^2+5(3.2-3.467)^2+5(5.0-3.467)^2\)</span></p>
<p><span class="math inline">\(SS_M=5(-1.267)^2+5(-0.267)^2+5(1.533)^2\)</span></p>
<p><span class="math inline">\(SS_M=8.025+0.355+11.755\)</span></p>
<p><span class="math inline">\(SS_M=20.135\)</span></p>
</div>
<div id="model-degrees-of-freedom" class="section level2">
<h2><span class="header-section-number">4.15</span> Model Degrees of Freedom</h2>
<p>How many values did we use to calculate SS<sub>M</sub>?</p>
<ul>
<li>We used the 3 means.</li>
</ul>
<p><span class="math inline">\(df_M=k-1=3-1=2\)</span></p>
</div>
<div id="residual-sum-of-squares-ssr" class="section level2">
<h2><span class="header-section-number">4.16</span> Residual Sum of Squares (SS<sub>R</sub>)</h2>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
<div id="step-3-calculate-ssr" class="section level2">
<h2><span class="header-section-number">4.17</span> Step 3: Calculate SS<sub>R</sub></h2>
<p><span class="math inline">\(SS_R=\mbox{sum}([x_i-\bar{x}_i]^2)\)</span></p>
<p><span class="math inline">\(SS_R=S^2_{group1}(n_1-1)+S^2_{group2}(n_2-1)+S^2_{group3}(n_3-1)\)</span></p>
<p><span class="math inline">\(SS_R=1.70(5-1)+1.70(5-1)+2.5(5-1)\)</span></p>
<p><span class="math inline">\(SS_R=(1.70\times4)+(1.70\times4)+(2.50\times4)\)</span></p>
<p><span class="math inline">\(SS_R=6.8+6.8+10\)</span></p>
<p><span class="math inline">\(SS_R=23.60\)</span></p>
</div>
<div id="residual-degrees-of-freedom" class="section level2">
<h2><span class="header-section-number">4.18</span> Residual Degrees of Freedom</h2>
<ul>
<li><p>How many values did we use to calculate SS<sub>R</sub>?</p></li>
<li><p>We used the 5 scores for each of the SS for each group.</p></li>
</ul>
<p><span class="math inline">\(df_R=df_{group1}+df_{group2}+df_{group3}\)</span></p>
<p><span class="math inline">\(df_R=(n_1-1)+(n_2-1)+(n_3-1)\)</span></p>
<p><span class="math inline">\(df_R=(5-1)+(5-1)+(5-1)\)</span></p>
<p><span class="math inline">\(df_R=12\)</span></p>
</div>
<div id="double-check" class="section level2">
<h2><span class="header-section-number">4.19</span> Double Check</h2>
<p><span class="math inline">\(SS_T=SS_R+SS_M\)</span></p>
<p><span class="math inline">\(43.74=20.14+23.60\)</span></p>
<p><span class="math inline">\(df_T=df_R+df_M\)</span></p>
<p><span class="math inline">\(14=2+12\)</span></p>
</div>
<div id="step-4-calculate-the-mean-squared-error" class="section level2">
<h2><span class="header-section-number">4.20</span> Step 4: Calculate the Mean Squared Error</h2>
<p><span class="math inline">\(MS_M=\frac{SS_M}{df_M}=\frac{20.135}{2}=10.067\)</span></p>
<p><span class="math inline">\(MS_R=\frac{SS_R}{df_R}=\frac{23.60}{12}=1.967\)</span></p>
</div>
<div id="step-5-calculate-the-f-ratio" class="section level2">
<h2><span class="header-section-number">4.21</span> Step 5: Calculate the <em>F</em>-Ratio</h2>
<p><span class="math inline">\(F=\frac{MS_M}{MS_R}\)</span></p>
<p><span class="math inline">\(F=\frac{MS_M}{MS_R}=\frac{10.067}{1.967}=5.12\)</span></p>
</div>
<div id="step-6-construct-a-summary-table" class="section level2">
<h2><span class="header-section-number">4.22</span> Step 6: Construct a Summary Table</h2>
<table>
<thead>
<tr class="header">
<th align="center">Source</th>
<th align="center">SS</th>
<th align="center">df</th>
<th align="center">MS</th>
<th align="center">F</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Model</td>
<td align="center">20.14</td>
<td align="center">2</td>
<td align="center">10.067</td>
<td align="center">5.12*</td>
</tr>
<tr class="even">
<td align="center">Residual</td>
<td align="center">23.60</td>
<td align="center">12</td>
<td align="center">1.967</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">Total</td>
<td align="center">43.74</td>
<td align="center">14</td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
</div>
<div id="multiple-comparison-tests" class="section level2">
<h2><span class="header-section-number">4.23</span> Multiple-Comparison Tests</h2>
<p>The ANOVA that you examined is used to test the hypothesis that there is no difference in the sample means among <em>k</em> treatment levels</p>
<p>However we cannot conclude, after doing the test, which of the mean values are different from one-another.</p>
</div>
<div id="tukey-test" class="section level2">
<h2><span class="header-section-number">4.24</span> Tukey Test</h2>
<p>Tukey test - balanced, orthogonal designs</p>
<p>Step 1: is to arrange and number all five sample means in order of increasing magnitude</p>
<p>Calculate the pairwise difference in sample means.</p>
<p>We use a <em>t</em>-test “analog” to calculate a q-statistic</p>
<p><em>S</em><sup>2</sup> is the error mean square by ANOVA computation</p>
<p><em>n</em> is the of data in each of groups B and A</p>
<p>Remember this is a completely balanced design.</p>
<p><span class="math inline">\(SE=\sqrt{\frac{s^2}{n}}\)</span></p>
<p><span class="math inline">\(q=\frac{\bar{Y}_B-\bar{Y}_A}{SE}\)</span></p>
<p>Start with the largest mean, vs. the smallest mean. Then when the first largest mean has been compared with increasingly large second means, use the second largest mean.</p>
<p>If the null hypothesis is accepted between two means then all other means within that range cannot be different.</p>
</div>
</div>
<div id="two-way-independent-anova" class="section level1">
<h1><span class="header-section-number">5</span> Two-Way Independent ANOVA</h1>
<p>Like one-way ANOVA this is a comparison of means test. In this module we will examine multifactor ANOVA.</p>
<ul>
<li><p>Multi-factorial ANOVA as a linear model</p></li>
<li><p>Hypotheses being tested</p></li>
<li><p>Interaction effects</p></li>
<li><p>Post-hoc tests</p></li>
<li><p>Non-parametric versions</p></li>
</ul>
<div id="what-is-two-way-independent-anova" class="section level2">
<h2><span class="header-section-number">5.1</span> What is Two-Way Independent ANOVA?</h2>
<p>Two independent variables</p>
<ul>
<li>Two-way (<em>n</em> = 2) factors</li>
</ul>
<p>Simultaneous analysis of two factors and measurement of mean response.</p>
<p>Terminology:</p>
<p>One <em>factor</em> termed A and one <em>factor</em> termed B.</p>
<p><em>a</em> is the number of levels in A.</p>
<p><em>b</em> is the number of levels in B.</p>
</div>
<div id="example-of-two-way-anova" class="section level2">
<h2><span class="header-section-number">5.2</span> Example of two-way ANOVA</h2>
<p>Researchers have sought to examine the effects of various types of music on agitation levels in patients in early and middle stages of Alzheimer’s disease.</p>
<p>Patients were selected based on their form of Alzheimer’s disease. Three forms of music were tested: easy listening, Mozart, and piano interludes. The response variable agitation level was scored.</p>
<p>Here is the design:</p>
<table>
<thead>
<tr class="header">
<th>Group</th>
<th align="center">Piano Interlude</th>
<th align="center">Mozart</th>
<th align="center">Easy Listening</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Early Stage ALzheimer’s</td>
<td align="center">21</td>
<td align="center">9</td>
<td align="center">29</td>
</tr>
<tr class="even">
<td></td>
<td align="center">24</td>
<td align="center">12</td>
<td align="center">26</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">22</td>
<td align="center">10</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td></td>
<td align="center">18</td>
<td align="center">5</td>
<td align="center">24</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">20</td>
<td align="center">9</td>
<td align="center">26</td>
</tr>
<tr class="even">
<td>Middle Stage Alzheimer’s</td>
<td align="center">22</td>
<td align="center">14</td>
<td align="center">15</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">20</td>
<td align="center">18</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td></td>
<td align="center">25</td>
<td align="center">11</td>
<td align="center">20</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">18</td>
<td align="center">9</td>
<td align="center">13</td>
</tr>
<tr class="even">
<td></td>
<td align="center">20</td>
<td align="center">13</td>
<td align="center">19</td>
</tr>
</tbody>
</table>
</div>
<div id="hypotheses-being-tested" class="section level2">
<h2><span class="header-section-number">5.3</span> Hypotheses Being Tested</h2>
<p>Three factor ANOVA:</p>
<ul>
<li>H<sub>O</sub>: Mean agitation is the same for each music type.</li>
<li>H<sub>O</sub> : Mean agitation is the same for each Alzheimer’s stage.</li>
<li>H<sub>O</sub> : Mean agitation is the same for all levels of music, independent of Alzheimer stage.</li>
</ul>
</div>
<div id="multiway-factorial-anova-hypotheses-being-tested" class="section level2">
<h2><span class="header-section-number">5.4</span> Multiway Factorial ANOVA Hypotheses Being Tested</h2>
<table>
<thead>
<tr class="header">
<th align="center">Popcorn</th>
<th align="center">Oil Amt.</th>
<th align="center">Batch</th>
<th align="center">Yeild</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Little</td>
<td align="center">Large</td>
<td align="center">8.2</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Little</td>
<td align="center">Large</td>
<td align="center">8.6</td>
</tr>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Lots</td>
<td align="center">Large</td>
<td align="center">10.4</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Lots</td>
<td align="center">Large</td>
<td align="center">9.2</td>
</tr>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Little</td>
<td align="center">Small</td>
<td align="center">9.9</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Little</td>
<td align="center">Small</td>
<td align="center">12.1</td>
</tr>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Lots</td>
<td align="center">Small</td>
<td align="center">10.6</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Lots</td>
<td align="center">Small</td>
<td align="center">18.0</td>
</tr>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Little</td>
<td align="center">Large</td>
<td align="center">8.8</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Little</td>
<td align="center">Large</td>
<td align="center">8.2</td>
</tr>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Lots</td>
<td align="center">Large</td>
<td align="center">8.8</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Lots</td>
<td align="center">Large</td>
<td align="center">9.8</td>
</tr>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Little</td>
<td align="center">Small</td>
<td align="center">10.1</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Little</td>
<td align="center">Small</td>
<td align="center">15.9</td>
</tr>
<tr class="odd">
<td align="center">Plain</td>
<td align="center">Lots</td>
<td align="center">Small</td>
<td align="center">7.4</td>
</tr>
<tr class="even">
<td align="center">Gourmet</td>
<td align="center">Lots</td>
<td align="center">Small</td>
<td align="center">16.0</td>
</tr>
</tbody>
</table>
</div>
<div id="hypotheses-being-tested-1" class="section level2">
<h2><span class="header-section-number">5.5</span> Hypotheses Being Tested</h2>
<p>Three factor ANOVA:</p>
<ul>
<li>H<sub>O</sub>: Yield is the same in all three Batch sizes</li>
<li>H<sub>O</sub> : Yield is the same in all three Oil amounts</li>
<li>H<sub>O</sub> : Yield is the same in all three Popcorn types</li>
<li>H<sub>O</sub> : The mean yield is the same for all levels of batch, independent of oil amount (Batch X Oil)</li>
<li>H<sub>O</sub> : The mean yield is the same for all levels of Oil amount, independent of popcorn type (Oil X Type)</li>
<li>H<sub>O</sub> : The mean yield is the same for all levels of batch, independent of popcorn type (Batch X Type)</li>
<li>H<sub>O</sub> : Differences in mean Yield among the batch, oil amount, and popcorn type are independent of the other factors + (Batch X Type X Oil)</li>
</ul>
<table>
<thead>
<tr class="header">
<th></th>
<th align="center">Df</th>
<th align="center">Sum Sq</th>
<th align="center">Mean Sq</th>
<th align="center">F value</th>
<th align="center">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>popcorn type</td>
<td align="center">1</td>
<td align="center">3.062</td>
<td align="center">3.062</td>
<td align="center">0.1731</td>
<td align="center">0.6883</td>
</tr>
<tr class="even">
<td>oil amount</td>
<td align="center">1</td>
<td align="center">0.062</td>
<td align="center">0.062</td>
<td align="center">0.0035</td>
<td align="center">0.9541</td>
</tr>
<tr class="odd">
<td>batch size</td>
<td align="center">1</td>
<td align="center">52.562</td>
<td align="center">52.562</td>
<td align="center">2.9717</td>
<td align="center">0.1230</td>
</tr>
<tr class="even">
<td>popcorn type:oil amount</td>
<td align="center">1</td>
<td align="center">27.562</td>
<td align="center">27.562</td>
<td align="center">1.5583</td>
<td align="center">0.2472</td>
</tr>
<tr class="odd">
<td>popcorn type:batch size</td>
<td align="center">1</td>
<td align="center">14.062</td>
<td align="center">14.062</td>
<td align="center">0.7951</td>
<td align="center">0.3986</td>
</tr>
<tr class="even">
<td>oil amount:batch size</td>
<td align="center">1</td>
<td align="center">0.063</td>
<td align="center">0.063</td>
<td align="center">0.0035</td>
<td align="center">0.9541</td>
</tr>
<tr class="odd">
<td>popcorn type:oil amount:batch size</td>
<td align="center">1</td>
<td align="center">1.563</td>
<td align="center">1.563</td>
<td align="center">0.0883</td>
<td align="center">0.7739</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td align="center">8</td>
<td align="center">141.500</td>
<td align="center">17.687</td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
</div>
<div id="benefit-of-factorial-designs" class="section level2">
<h2><span class="header-section-number">5.6</span> Benefit of Factorial Designs</h2>
<p>1.) The experimental design is an efficient design to test multiple hypotheses simultaneously.</p>
<p>2.) We can look at how variables interact, this process is called ‘interaction’.</p>
<ul>
<li><p>Show how the effects that one level of one group (or factor) might depend on the effects of level in another group.</p></li>
<li><p>Are often more interesting than main effects.</p></li>
</ul>
</div>
<div id="a-worked-example-of-factorial-design" class="section level2">
<h2><span class="header-section-number">5.7</span> A worked example of factorial design</h2>
<p>Testing the effects of the pH of soil and amount of sunlight exposure (full or partial) on mean plant height.</p>
<p>We will test:</p>
</div>
<div id="hypotheses-being-tested-2" class="section level2">
<h2><span class="header-section-number">5.8</span> Hypotheses Being Tested</h2>
<ul>
<li>H<sub>O</sub>: Mean plant height is the same in all sunlight treatments.</li>
<li>H<sub>O</sub> : Mean plant height is the same in all pH treatments.</li>
<li>H<sub>O</sub> : There is no significant interaction of ph and sunlight.</li>
</ul>
</div>
<div id="remeber-the-terminology" class="section level2">
<h2><span class="header-section-number">5.9</span> Remeber the terminology</h2>
<ul>
<li>Factor A (pH), levels = 6, 7, 8</li>
<li>Factor B (Sun), levels = full, partial</li>
</ul>
<p>The response is the height of the plant at the end of the experiment.</p>
<p>The experiment has two “levels” for the factor “B” (b = 2) and three “levels” for the factor “A” (a = 3).</p>
<p>Thus, there are <span class="math inline">\(ab = 3\times2=6\)</span> unique combinations of sun and pH With each combination.</p>
<p>We have <em>r</em> = 8 observations for each combination. <em>r</em> is called the number of replicates, in each cell.</p>
<p>The total number of replicates (<em>n</em>) is:</p>
<p><span class="math inline">\(N = abr = 3\times2\times8 = 48\)</span>.</p>
<p>The amounts <span class="math inline">\(Y_{i,j,k}\)</span> is the amount of plant height for each replicate (<em>k</em> = 1 to 8) with sun i, (<em>i</em> = 1, 2) at pH <em>j</em>, (<em>j</em> = 1, 2, 3).</p>
<p>Treatment and level-specific data for the plant height (cm):</p>
<table>
<thead>
<tr class="header">
<th align="center">pH (Factor A, <em>a</em> levels)</th>
<th align="center">6</th>
<th align="center">6</th>
<th align="center">7</th>
<th align="center">7</th>
<th align="center">8</th>
<th align="center">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Sun (Factor B, <em>b</em> levels)</td>
<td align="center">Full</td>
<td align="center">Partial</td>
<td align="center">Full</td>
<td align="center">Partial</td>
<td align="center">Full</td>
<td align="center">Partial</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">65</td>
<td align="center">50</td>
<td align="center">70</td>
<td align="center">45</td>
<td align="center">55</td>
<td align="center">30</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">70</td>
<td align="center">55</td>
<td align="center">65</td>
<td align="center">60</td>
<td align="center">65</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">60</td>
<td align="center">80</td>
<td align="center">60</td>
<td align="center">85</td>
<td align="center">70</td>
<td align="center">30</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">60</td>
<td align="center">65</td>
<td align="center">70</td>
<td align="center">65</td>
<td align="center">55</td>
<td align="center">55</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">60</td>
<td align="center">70</td>
<td align="center">65</td>
<td align="center">70</td>
<td align="center">55</td>
<td align="center">35</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">55</td>
<td align="center">75</td>
<td align="center">60</td>
<td align="center">70</td>
<td align="center">60</td>
<td align="center">20</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center">60</td>
<td align="center">75</td>
<td align="center">60</td>
<td align="center">80</td>
<td align="center">50</td>
<td align="center">45</td>
</tr>
<tr class="odd">
<td align="center"></td>
<td align="center">55</td>
<td align="center">65</td>
<td align="center">50</td>
<td align="center">60</td>
<td align="center">50</td>
<td align="center">40</td>
</tr>
<tr class="even">
<td align="center">Total</td>
<td align="center">485</td>
<td align="center">535</td>
<td align="center">500</td>
<td align="center">535</td>
<td align="center">460</td>
<td align="center">285</td>
</tr>
<tr class="odd">
<td align="center">Mean</td>
<td align="center">60.625</td>
<td align="center">66.875</td>
<td align="center">62.50</td>
<td align="center">66.875</td>
<td align="center">57.50</td>
<td align="center">35.625</td>
</tr>
<tr class="even">
<td align="center">Variance</td>
<td align="center">24.55</td>
<td align="center">106.70</td>
<td align="center">42.86</td>
<td align="center">156.70</td>
<td align="center">50.00</td>
<td align="center">117.41</td>
</tr>
</tbody>
</table>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="step-1-calculate-sst-1" class="section level2">
<h2><span class="header-section-number">5.10</span> Step 1: Calculate SS<sub>T</sub></h2>
<p><span class="math inline">\(Grand \: Mean = \bar{X} = 58.33\)</span></p>
<p><span class="math inline">\(SS_T=\sum_{i=1}^{a}\sum_{j=1}^{b}\sum_{l=1}^{n}({X_{i,j,l} - \bar{X}})^2\)</span></p>
<p><span class="math inline">\(SS_T=8966.66\)</span></p>
</div>
<div id="step-2-calculate-ssm-1" class="section level2">
<h2><span class="header-section-number">5.11</span> Step 2: Calculate SS<sub>M</sub></h2>
<table>
<thead>
<tr class="header">
<th align="center">pH (Factor A, <em>a</em> levels)</th>
<th align="center">6</th>
<th align="center">6</th>
<th align="center">7</th>
<th align="center">7</th>
<th align="center">8</th>
<th align="center">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Sun (Factor B, <em>b</em> levels)</td>
<td align="center">Full</td>
<td align="center">Partial</td>
<td align="center">Full</td>
<td align="center">Partial</td>
<td align="center">Full</td>
<td align="center">Partial</td>
</tr>
<tr class="even">
<td align="center">Mean</td>
<td align="center">60.625</td>
<td align="center">66.875</td>
<td align="center">62.50</td>
<td align="center">66.875</td>
<td align="center">57.50</td>
<td align="center">35.625</td>
</tr>
</tbody>
</table>
<p>Here we evaluate main effects and interaction effects.</p>
<p><span class="math inline">\(SS_M=n\sum_{i=1}^{a}\sum_{j = 1}^{b}({\bar{X}_{ij}}-\bar{X})^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{M}=8(60.625-58.33)^2+8(66.875-58.33)^2+8(62.5-58.33)^2+8(66.875-58.33)^2+8(57.5-58.33)^2+8(35.625-58.33)^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{M}=8(2.295)^2+8(8.545)^2+8(4.17)^2+8(8.545)^2+8(-0.83)^2+8(-22.705)^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{M}=42.1362+584.1362+139.1112+584.1362+5.5112+4124.1362\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{M}=5479.17\)</span></p>
</div>
<div id="step-2a-calculate-ssa" class="section level2">
<h2><span class="header-section-number">5.12</span> Step 2a: Calculate SS<sub>A</sub></h2>
<p>Mean “Full Sun”: 60.21 cm</p>
<table>
<thead>
<tr class="header">
<th align="center">SS<sub>A</sub></th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">65</td>
<td align="center">70</td>
<td align="center">55</td>
</tr>
<tr class="even">
<td align="center">70</td>
<td align="center">65</td>
<td align="center">65</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">60</td>
<td align="center">70</td>
</tr>
<tr class="even">
<td align="center">60</td>
<td align="center">70</td>
<td align="center">55</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">65</td>
<td align="center">55</td>
</tr>
<tr class="even">
<td align="center">55</td>
<td align="center">60</td>
<td align="center">60</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">60</td>
<td align="center">50</td>
</tr>
<tr class="even">
<td align="center">55</td>
<td align="center">50</td>
<td align="center">50</td>
</tr>
</tbody>
</table>
<p>Mean “Partial Sun”: 56.46 cm</p>
<table>
<thead>
<tr class="header">
<th align="center">SS<sub>A</sub></th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">50</td>
<td align="center">45</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td align="center">55</td>
<td align="center">60</td>
<td align="center">30</td>
</tr>
<tr class="odd">
<td align="center">80</td>
<td align="center">85</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td align="center">65</td>
<td align="center">65</td>
<td align="center">55</td>
</tr>
<tr class="odd">
<td align="center">70</td>
<td align="center">70</td>
<td align="center">35</td>
</tr>
<tr class="even">
<td align="center">75</td>
<td align="center">70</td>
<td align="center">20</td>
</tr>
<tr class="odd">
<td align="center">75</td>
<td align="center">80</td>
<td align="center">45</td>
</tr>
<tr class="even">
<td align="center">65</td>
<td align="center">60</td>
<td align="center">40</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(SS_{A} = {rb}\sum_{i=1}^a(\overline{X}_{i} - \overline{X})^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{Sun}=24(60.21-58.33)^2+24(56.46-58.33)^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{Sun}=24(1.88)^2+24(-1.87)^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{Sun}=84.8256+83.9256\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{Sun}=168.75\)</span></p>
</div>
<div id="step-2b-calculate-ssb" class="section level2">
<h2><span class="header-section-number">5.13</span> Step 2b: Calculate SS<sub>B</sub></h2>
<ul>
<li>Factor B is pH.</li>
</ul>
<p>pH = 6</p>
<p>Mean <span class="math inline">\(\mbox{pH}_6\)</span> = 63.75</p>
<table>
<thead>
<tr class="header">
<th align="center">SS<sub>B</sub></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">65</td>
<td align="center">50</td>
</tr>
<tr class="even">
<td align="center">70</td>
<td align="center">55</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">80</td>
</tr>
<tr class="even">
<td align="center">60</td>
<td align="center">65</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">70</td>
</tr>
<tr class="even">
<td align="center">55</td>
<td align="center">75</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">75</td>
</tr>
<tr class="even">
<td align="center">55</td>
<td align="center">65</td>
</tr>
</tbody>
</table>
<p>pH = 7</p>
<p>Mean <span class="math inline">\(\mbox{pH}_7\)</span> = 64.68</p>
<table>
<thead>
<tr class="header">
<th align="center">SS<sub>B</sub></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">70</td>
<td align="center">45</td>
</tr>
<tr class="even">
<td align="center">65</td>
<td align="center">60</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">85</td>
</tr>
<tr class="even">
<td align="center">70</td>
<td align="center">65</td>
</tr>
<tr class="odd">
<td align="center">65</td>
<td align="center">70</td>
</tr>
<tr class="even">
<td align="center">60</td>
<td align="center">70</td>
</tr>
<tr class="odd">
<td align="center">60</td>
<td align="center">80</td>
</tr>
<tr class="even">
<td align="center">50</td>
<td align="center">60</td>
</tr>
</tbody>
</table>
<p>pH = 8</p>
<p>Mean <span class="math inline">\(\mbox{pH}_8\)</span> = 46.56</p>
<table>
<thead>
<tr class="header">
<th align="center">SS<sub>B</sub></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">55</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td align="center">65</td>
<td align="center">30</td>
</tr>
<tr class="odd">
<td align="center">70</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td align="center">55</td>
<td align="center">55</td>
</tr>
<tr class="odd">
<td align="center">55</td>
<td align="center">35</td>
</tr>
<tr class="even">
<td align="center">60</td>
<td align="center">20</td>
</tr>
<tr class="odd">
<td align="center">50</td>
<td align="center">45</td>
</tr>
<tr class="even">
<td align="center">50</td>
<td align="center">40</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(SS_B = ra\sum_{j=1}^b(\overline{X}_{j} - \overline{X})^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{pH}=16(63.75-58.33)^2+16(64.68-58.33)^2+16(46.56-58.33)^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{pH}=16(5.42)^2+16(6.3575)^2+16(-11.7675)^2\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{pH}=470.0224+646.6849+2215.5849\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{pH}=3332.292\)</span></p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="step-2c-calculate-ssaxb" class="section level2">
<h2><span class="header-section-number">5.14</span> Step 2c: Calculate SS<sub>(AxB)</sub></h2>
<p><span class="math inline">\(\mbox{SS}_\mbox{M}=\mbox{SS}_{\mbox{A}{\times}\mbox{B}} + \mbox{SS}_\mbox{A}+\mbox{SS}_\mbox{B}\)</span></p>
<p><span class="math inline">\(\mbox{SS}_{\mbox{A}{\times}\mbox{B}}=\mbox{SS}_\mbox{M}-\mbox{SS}_\mbox{A}-\mbox{SS}_\mbox{B}\)</span></p>
<p><span class="math inline">\(\mbox{SS}_{\mbox{Sun}{\times}\mbox{pH}}=\mbox{SS}_\mbox{M}-\mbox{SS}_\mbox{Sun}-\mbox{SS}_\mbox{pH}\)</span></p>
<p><span class="math inline">\(=5479.167-168.75-3332.292\)</span></p>
<p><span class="math inline">\(=1978.125\)</span></p>
</div>
<div id="step-3-calculate-ssr-1" class="section level2">
<h2><span class="header-section-number">5.15</span> Step 3: Calculate SS<sub>R</sub></h2>
<p>The residual sum of squares is calculated in the same way as for one-way ANOVA .</p>
<p>Represents individual differences in performance or the variance that can’t be explained by factors that were systematically manipulated.</p>
<p>We saw in one-way ANOVA that the value is calculated by taking the squared error between each data point and its corresponding group mean.</p>
<p>So, we use the individual variances of each group and multiply them by one less than the number of people within the group (n).</p>
<p>We have the individual group variances: there were eight people in each group (therefore, <em>n</em> = 8).</p>
<p><span class="math inline">\(\mbox{SS}_\mbox{R}=s^2_{group1}(n_1-1)+s^2_{group2}(n_2-1)+s^2_{group3}(n_3-1)+s^2_{group \: n}(n_n-1)\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{R}=s^2_{group1}(n_1-1)+s^2_{group2}(n_2-1)+s^2_{group3}(n_3-1)+s^2_{group4}(n_4-1)+s^2_{group5}(n_5-1)+s^2_{group6}(n_6-1)\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{R}=(24.55\times7)+(106.7\times7)+(42.86\times7)+(156.7\times7)+(50\times7)+(117.41\times7)\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{R}=171.85+746.9+300+1096.9+350+821.87\)</span></p>
<p><span class="math inline">\(\mbox{SS}_\mbox{R}=3487.52\)</span></p>
</div>
<div id="degrees-of-freedom-and-mean-square-calculations" class="section level2">
<h2><span class="header-section-number">5.16</span> Degrees of Freedom and Mean Square Calculations</h2>
<table>
<thead>
<tr class="header">
<th align="center">Source</th>
<th align="center">SS</th>
<th align="center">df</th>
<th align="center">MS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Factor A</td>
<td align="center"><span class="math inline">\(SS_A\)</span></td>
<td align="center">a-1</td>
<td align="center"><span class="math inline">\(\frac{SS_A}{a-1}\)</span></td>
</tr>
<tr class="even">
<td align="center">Factor B</td>
<td align="center"><span class="math inline">\(SS_B\)</span></td>
<td align="center">b-1</td>
<td align="center"><span class="math inline">\(\frac{SS_B}{b-1}\)</span></td>
</tr>
<tr class="odd">
<td align="center">Factor A x B</td>
<td align="center"><span class="math inline">\(SS_{AB}\)</span></td>
<td align="center">(a-1)(b-1)</td>
<td align="center"><span class="math inline">\(\frac{SS_{AB}}{(a-1)(b-1)}\)</span></td>
</tr>
<tr class="even">
<td align="center">Error</td>
<td align="center">SSE</td>
<td align="center">N-ab</td>
<td align="center"><span class="math inline">\(\frac{SSE}{N-ab}\)</span></td>
</tr>
<tr class="odd">
<td align="center">Total</td>
<td align="center">SST</td>
<td align="center">N-1</td>
<td align="center"></td>
</tr>
</tbody>
</table>
</div>
<div id="interpreting-factorial-anova" class="section level2">
<h2><span class="header-section-number">5.17</span> Interpreting Factorial ANOVA</h2>
<table>
<thead>
<tr class="header">
<th>Response</th>
<th align="center">Plant Growth</th>
<th align="center"></th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td align="center">Sum Sq</td>
<td align="center">Df</td>
<td align="center"><em>F</em> value</td>
<td align="center">Pr(&gt;<em>F</em>)</td>
</tr>
<tr class="even">
<td>Sunlight</td>
<td align="center">169</td>
<td align="center">1</td>
<td align="center">2.0323</td>
<td align="center">0.1614</td>
</tr>
<tr class="odd">
<td>pH</td>
<td align="center">3332</td>
<td align="center">2</td>
<td align="center">20.0654</td>
<td align="center">7.649e-07</td>
</tr>
<tr class="even">
<td>Sunlight:pH</td>
<td align="center">1978</td>
<td align="center">2</td>
<td align="center">11.9113</td>
<td align="center">7.987e-05</td>
</tr>
<tr class="odd">
<td>residuals</td>
<td align="center">3488</td>
<td align="center">42</td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
</div>
<div id="interpretation-main-effect-ph" class="section level2">
<h2><span class="header-section-number">5.18</span> Interpretation: Main Effect pH</h2>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<ul>
<li>There was a significant main effect of the amount of pH in the soil on the height of the plant, F(2, 42) = 20.07, p &lt; 0.001</li>
</ul>
</div>
<div id="interpretation-main-effect-sun" class="section level2">
<h2><span class="header-section-number">5.19</span> Interpretation: Main Effect Sun</h2>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<ul>
<li>There was a non-significant main effect of sunlight exposure on the plant height, F(1, 42) = 2.03, p = 0.161.</li>
</ul>
</div>
<div id="interpretation-interaction-effects" class="section level2">
<h2><span class="header-section-number">5.20</span> Interpretation: Interaction Effects</h2>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<ul>
<li>There was a significant interaction between the amount of pH in the soil and the amount of sunlight exposure, on the height of the plant, F(2, 42) = 11.91, p &lt; .001.</li>
<li>Non-parallel lines indicate such an interaction: For low pH full and partial sunlight, scores do not change much.</li>
<li>At a high pH, partial sunlight scores plummet but full sunlight scores remain fairly high. So, the interaction is caused by a difference between sunlight exposure in the height of plants.</li>
</ul>
</div>
<div id="factorial-anova-as-regression" class="section level2">
<h2><span class="header-section-number">5.21</span> Factorial ANOVA as Regression</h2>
<table>
<thead>
<tr class="header">
<th>pH</th>
<th align="center">6</th>
<th align="center">6</th>
<th align="center">7</th>
<th align="center">7</th>
<th align="center">8</th>
<th align="center">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sunlight</td>
<td align="center">Full</td>
<td align="center">Partial</td>
<td align="center">Full</td>
<td align="center">Partial</td>
<td align="center">Full</td>
<td align="center">Partial</td>
</tr>
<tr class="even">
<td></td>
<td align="center">65</td>
<td align="center">50</td>
<td align="center">70</td>
<td align="center">45</td>
<td align="center">55</td>
<td align="center">30</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">70</td>
<td align="center">55</td>
<td align="center">65</td>
<td align="center">60</td>
<td align="center">65</td>
<td align="center">30</td>
</tr>
<tr class="even">
<td></td>
<td align="center">60</td>
<td align="center">80</td>
<td align="center">60</td>
<td align="center">85</td>
<td align="center">70</td>
<td align="center">30</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">60</td>
<td align="center">65</td>
<td align="center">70</td>
<td align="center">65</td>
<td align="center">55</td>
<td align="center">55</td>
</tr>
<tr class="even">
<td></td>
<td align="center">60</td>
<td align="center">70</td>
<td align="center">65</td>
<td align="center">70</td>
<td align="center">55</td>
<td align="center">35</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">55</td>
<td align="center">75</td>
<td align="center">60</td>
<td align="center">70</td>
<td align="center">60</td>
<td align="center">20</td>
</tr>
<tr class="even">
<td></td>
<td align="center">60</td>
<td align="center">75</td>
<td align="center">60</td>
<td align="center">80</td>
<td align="center">50</td>
<td align="center">45</td>
</tr>
<tr class="odd">
<td></td>
<td align="center">55</td>
<td align="center">65</td>
<td align="center">50</td>
<td align="center">60</td>
<td align="center">50</td>
<td align="center">40</td>
</tr>
<tr class="even">
<td>Total</td>
<td align="center">485</td>
<td align="center">535</td>
<td align="center">500</td>
<td align="center">535</td>
<td align="center">460</td>
<td align="center">285</td>
</tr>
<tr class="odd">
<td>Mean</td>
<td align="center">60.625</td>
<td align="center">66.875</td>
<td align="center">62.50</td>
<td align="center">66.875</td>
<td align="center">57.50</td>
<td align="center">35.625</td>
</tr>
<tr class="even">
<td>Variance</td>
<td align="center">24.55</td>
<td align="center">106.70</td>
<td align="center">42.86</td>
<td align="center">156.70</td>
<td align="center">50.00</td>
<td align="center">117.41</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(outcome_i = (\mbox{model})+\mbox{error}_i\)</span></p>
<p><span class="math inline">\(plant height_i=(b_0+b_{1}\mbox{Sunlight}_i+b_2\mbox{pH}_i)+\varepsilon_i\)</span></p>
<p><span class="math inline">\(plant height_i=(b_0+b_1A_i+b_2B_i+b_3AB_i)+\varepsilon_i\)</span></p>
<p><span class="math inline">\(plant height_i=(b_0+b_1Sunlight_i+b_2pH_i+b_3interaction_i)+\varepsilon_i\)</span></p>
<ul>
<li><p>How do we code the interaction term?</p></li>
<li><p>Multiply the variables</p></li>
<li><p><em>A</em> x <em>B</em></p></li>
</ul>
<table>
<thead>
<tr class="header">
<th>Sunlight</th>
<th align="center">pH</th>
<th align="center">Dummy (Sunlight)</th>
<th align="center">Dummy (pH)</th>
<th align="center">Interaction</th>
<th align="center">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Partial</td>
<td align="center">6</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">66.875</td>
</tr>
<tr class="even">
<td>Partial</td>
<td align="center">8</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">35.625</td>
</tr>
<tr class="odd">
<td>Full</td>
<td align="center">6</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">60.625</td>
</tr>
<tr class="even">
<td>Full</td>
<td align="center">8</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">57.500</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(plant height_i=(b_0+b_1Sunlight_i+b_2pH_i+b_3interaction_i)+\varepsilon_i\)</span></p>
<p><span class="math inline">\(\bar{Y}_{partial,6}=b_0+(b_1\times0)+(b_2\times0)+(b_3\times0)\)</span></p>
<p><span class="math inline">\(b_0=\bar{Y}_{partial,6}\)</span></p>
<p><span class="math inline">\(b_0=66.875\)</span></p>
<table>
<thead>
<tr class="header">
<th>Sunlight</th>
<th align="center">pH</th>
<th align="center">Dummy (Sunlight)</th>
<th align="center">Dummy (pH)</th>
<th align="center">Interaction</th>
<th align="center">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Partial</td>
<td align="center">6</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">66.875</td>
</tr>
<tr class="even">
<td>Partial</td>
<td align="center">8</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">35.625</td>
</tr>
<tr class="odd">
<td>Full</td>
<td align="center">6</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">60.625</td>
</tr>
<tr class="even">
<td>Full</td>
<td align="center">8</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">57.500</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\bar{Y}_{Full,6}=b_0+(b_1\times1)+(b_2\times0)+(b_3\times0)\)</span></p>
<p><span class="math inline">\(\bar{Y}_{Full,6}=b_0+b_1\)</span></p>
<p><span class="math inline">\(\bar{Y}_{Full,6}=\bar{Y}_{partial,6}+b_1\)</span></p>
<p><span class="math inline">\(b_1=\bar{Y}_{Full,6}-\bar{Y}_{partial,6}\)</span></p>
<p><span class="math inline">\(b_1=60.625-66.875\)</span></p>
<p><span class="math inline">\(b_1=-6.25\)</span></p>
<table>
<thead>
<tr class="header">
<th>Sunlight</th>
<th align="center">pH</th>
<th align="center">Dummy (Sunlight)</th>
<th align="center">Dummy (pH)</th>
<th align="center">Interaction</th>
<th align="center">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Partial</td>
<td align="center">6</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">66.875</td>
</tr>
<tr class="even">
<td>Partial</td>
<td align="center">8</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">35.625</td>
</tr>
<tr class="odd">
<td>Full</td>
<td align="center">6</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">60.625</td>
</tr>
<tr class="even">
<td>Full</td>
<td align="center">8</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">57.500</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\bar{Y}_{partial,4 \: pH}=b_0+(b_1\times0)+(b_2\times1)+(b_3\times0)\)</span></p>
<p><span class="math inline">\(\bar{Y}_{partial,4 \: pH}=b_0+b_2\)</span></p>
<p><span class="math inline">\(\bar{Y}_{partial,4 \: pH}=\bar{Y}_{partial,6}+b_2\)</span></p>
<p><span class="math inline">\(b_2=\bar{Y}_{partial,4 \: pH}-\bar{Y}_{partial,6}\)</span></p>
<table>
<thead>
<tr class="header">
<th>Sunlight</th>
<th align="center">pH</th>
<th align="center">Dummy (Sunlight)</th>
<th align="center">Dummy (pH)</th>
<th align="center">Interaction</th>
<th align="center">Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Partial</td>
<td align="center">6</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">66.875</td>
</tr>
<tr class="even">
<td>Partial</td>
<td align="center">8</td>
<td align="center">0</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">35.625</td>
</tr>
<tr class="odd">
<td>Full</td>
<td align="center">6</td>
<td align="center">1</td>
<td align="center">0</td>
<td align="center">0</td>
<td align="center">60.625</td>
</tr>
<tr class="even">
<td>Full</td>
<td align="center">8</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">1</td>
<td align="center">57.500</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\bar{Y}_{Full,4 \: pH}=b_0+(b_1\times1)+(b_2\times1)+(b_3\times1)\)</span></p>
<p><span class="math inline">\(\bar{Y}_{Full,4 \: pH}=b_0+b_1+b_2+b_3\)</span></p>
<p><span class="math inline">\(\bar{Y}_{Full,4 \: pH}=\bar{Y}_{partial,6}+(\bar{Y}_{Full,6}-\bar{Y}_{partial,6})+(\bar{Y}_{partial,4 \: pH}-\bar{Y}_{partial,6})+b_3\)</span></p>
<p><span class="math inline">\(\bar{Y}_{Full,4 \: pH}=\bar{Y}_{Full,6}+\bar{Y}_{partial,4 \: pH}-\bar{Y}_{partial,6}+b_3\)</span></p>
<p><span class="math inline">\(b_3=\bar{Y}_{partial,6}-\bar{Y}_{Full,6}+\bar{Y}_{Full,4 \: pH}-\bar{Y}_{partial,4 \: pH}\)</span></p>
<p><span class="math inline">\(b_3=66.875-60.625+57.500-35.625\)</span></p>
<p><span class="math inline">\(b_3=28.125\)</span></p>
</div>
<div id="interaction-effects" class="section level2">
<h2><span class="header-section-number">5.22</span> Interaction Effects</h2>
<p>Experiment: we are interested in oxygen consumption of two species of limpets in different concentration of seawater.</p>
<ul>
<li>Factor A is the species of limpet (levels, a)</li>
<li>Factor B is the concentration of SW as a function of maximum salinity - 100, 75, and 50 % (levels, b)</li>
</ul>
<table>
<thead>
<tr class="header">
<th>Completed anova</th>
<th align="center"></th>
<th align="center"></th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Source of variation</td>
<td align="center">df</td>
<td align="center">SS</td>
<td align="center">MS</td>
</tr>
<tr class="even">
<td>Species</td>
<td align="center">1</td>
<td align="center">16.6380</td>
<td align="center">16.638 ns</td>
</tr>
<tr class="odd">
<td>salinities</td>
<td align="center">2</td>
<td align="center">10.3566</td>
<td align="center">5.178 ns</td>
</tr>
<tr class="even">
<td>Sp X Sal</td>
<td align="center">2</td>
<td align="center">194.8907</td>
<td align="center">97.445 **</td>
</tr>
<tr class="odd">
<td>Error</td>
<td align="center">42</td>
<td align="center">401.5213</td>
<td align="center">9.560</td>
</tr>
<tr class="even">
<td>Total</td>
<td align="center">47</td>
<td align="center">623.4066</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>When the two factors are identified as A and B, the interaction is identified as the A X B interaction.</p>
<p>Variability not accounted for by A and B alone.</p>
<p>Interaction: The effect of one factor in the presence of a particular level of another factor.</p>
<p>There is an interaction between two factors if the effect of one factor depends on the levels of the second factor.</p>
<table>
<thead>
<tr class="header">
<th></th>
<th align="center">Species</th>
<th align="center">Species</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Seawater Concentration</td>
<td align="center">A. scabra</td>
<td align="center">A. digitalis</td>
<td align="center">Mean</td>
</tr>
<tr class="even">
<td>100%</td>
<td align="center">10.56</td>
<td align="center">7.43</td>
<td align="center">9.00</td>
</tr>
<tr class="odd">
<td>75%</td>
<td align="center">7.89</td>
<td align="center">7.34</td>
<td align="center">10.11</td>
</tr>
<tr class="even">
<td>50%</td>
<td align="center">12.17</td>
<td align="center">12.33</td>
<td align="center">9.76</td>
</tr>
<tr class="odd">
<td>Mean</td>
<td align="center">10.21</td>
<td align="center">9.03</td>
<td align="center">9.62</td>
</tr>
</tbody>
</table>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<ul>
<li><p>The response to salinity differs between the two species</p></li>
<li><p>At 75% salinity A. scabra consumes the least oxygen and A. digitalis consumes the most.</p></li>
<li><p>Therefore a simple statement about the species response to salinity is not clear; all we can really say is:</p></li>
<li><p>The pattern of response to changes in salinity differed in the two species.</p></li>
<li><p>The difference among levels of one factor is not constant at all levels of the second factor</p></li>
<li><p>“It is generally not useful to speak of an individual factor effect - even if its <em>F</em> is significant - if there is a significant interaction effect” - Zar</p></li>
</ul>
</div>
<div id="post-hoc-tests" class="section level2">
<h2><span class="header-section-number">5.23</span> Post-hoc Tests</h2>
<p>Tukey test - balanced, orthogonal designs</p>
<ul>
<li>Step one: is to arrange and number all five sample means in order of increasing magnitude</li>
<li>Calculate the pairwise difference in sample means.</li>
</ul>
<p>We use a <em>t</em>-test “analog” to calculate a q-statistic</p>
<p>Scheffe’s test</p>
<p>Examine multiple contrasts:</p>
<ul>
<li>ideas is to compare combinations of samples to each other instead of the comparison among individual k levels.</li>
</ul>
<p>Compare the mean outflow volume of four different rivers: 5 vs 1,2,3,4</p>
<p><span class="math inline">\(H_0:\mu_2/3+\mu_4/3+\mu_3/3-\mu_5=0\)</span></p>
<p><span class="math inline">\(H_0:(\mu_2+\mu_4+\mu_3)/3=\mu_5\)</span></p>
<p><span class="math inline">\(c_2=\frac{1}{3}, \: c_4=\frac{1}{3}, \: c_3=\frac{1}{3}, \: and \: c_5=-1\)</span></p>
<p><Br></p>
<p>Alternatives multiple contrasts:</p>
<p><span class="math inline">\(H_0:(\mu_1+\mu_5)/2-(\mu_2+\mu_4+\mu_3)/3=0\)</span></p>
<p><span class="math inline">\(H_0:\mu_1-(\mu_2+\mu_4+\mu_3)/3\)</span></p>
<p>Test Statistic:</p>
<p><span class="math inline">\(s=\frac{|\sum c_i\bar{Y}_i|}{SE}\)</span></p>
<ul>
<li>Where</li>
</ul>
<p><span class="math inline">\(SE=\sqrt{s^2(\sum \frac{c^2_i}{n_i})}\)</span></p>
<ul>
<li>and the critical value of the test is</li>
</ul>
<p><span class="math inline">\(S_{\alpha}=\sqrt{(k-1)F_{\alpha(1),k-1,N-k}}\)</span></p>
</div>
<div id="non-parametric-tests" class="section level2">
<h2><span class="header-section-number">5.24</span> Non-Parametric Tests</h2>
<p>Violations of the assumptions</p>
<p>We assume equality of variance - ANOVA is a robust test.</p>
<p>Robust to unbalanced design.</p>
<p>How to deal with outliers:</p>
<ul>
<li>use in analysis if they are valid data.</li>
</ul>
<p>Test of normality: Shapiro Wilks</p>
<p>Test of equality of variance: Bartletts test.</p>
<p>Nonparametric analysis of variance.</p>
<p>If k &gt; 2</p>
<p>Kruskal-Wallis test - analysis of variance by rank</p>
<p>Power increases with sample size.</p>
<p>If k = 2 the Kruskal-Wallis is equivalent to the Mann-Whitney test.</p>
<p><span class="math inline">\(H=\frac{12}{N(N+1)}\sum ^k_{i=1}\frac{R^2_i}{n_i}-3(N+1)\)</span></p>
<p>If there are tied ranks</p>
<ul>
<li>H needs to be corrected using a correction factor C.</li>
</ul>
<p><span class="math inline">\(C=1-\frac{\sum t}{N^3-N}\)</span></p>
<p><span class="math inline">\(H_c=\frac{H}{C}\)</span></p>
<p><span class="math inline">\(\sum t=\sum (t^3_i-t_i)\)</span></p>
<ul>
<li>t<sub>i</sub> is the number of tied ranks.</li>
</ul>
<p>A limnologist obtained eight containers of water from each of four ponds. The pH of each water sample was measured. The data are arranged in ascending order within each pond. (One of the containers from pond 3 was lost, so n<sub>3</sub> = 7, instead of 8; but the test procedure does not require equal numbers of data in each group.) The rank of each datum is shown parenthetically.</p>
<ul>
<li>H<sub>0</sub>: pH is the same in all four ponds.</li>
<li>H<sub>A</sub>: pH is not the same in all four ponds.</li>
</ul>
<p><Br></p>
<table>
<thead>
<tr class="header">
<th align="center">Pond 1</th>
<th align="center">Pond 2</th>
<th align="center">Pond 3</th>
<th align="center">Pond 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">7.68 (1)</td>
<td align="center">7.71 (6*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.71 (6*)</td>
</tr>
<tr class="even">
<td align="center">7.69 (2)</td>
<td align="center">7.73 (10)</td>
<td align="center">7.75 (16)</td>
<td align="center">7.71 (6*)</td>
</tr>
<tr class="odd">
<td align="center">7.70 (3.5*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.77 (18)</td>
<td align="center">7.74 (13.5)</td>
</tr>
<tr class="even">
<td align="center">7.70 (3.5*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.79 (22)</td>
</tr>
<tr class="odd">
<td align="center">7.72 (8)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.80 (23.5*)</td>
<td align="center">7.81 (26*)</td>
</tr>
<tr class="even">
<td align="center">7.73 (10*)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.81 (26*)</td>
<td align="center">7.85 (29)</td>
</tr>
<tr class="odd">
<td align="center">7.73 (10*)</td>
<td align="center">7.80(23.5*)</td>
<td align="center">7.84 (28)</td>
<td align="center">7.87 (30)</td>
</tr>
<tr class="even">
<td align="center">7.76 (17)</td>
<td align="center">7.81 (26*)</td>
<td align="center"></td>
<td align="center">7.91 (31)</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th>n<sub>1</sub> =8</th>
<th>n<sub>2</sub> =8</th>
<th>n<sub>3</sub> =7</th>
<th>n<sub>4</sub> =8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R<sub>1</sub> =55</td>
<td>R<sub>2</sub> =132.5</td>
<td>R<sub>3</sub> =145</td>
<td>R<sub>4</sub> =163.5</td>
</tr>
</tbody>
</table>
<p>*tied ranks</p>
<p><span class="math inline">\(H=\frac{12}{N(N+1)}\sum ^k_{i=1}\frac{R^2_i}{n_i}-3(N+1)\)</span></p>
<p><span class="math inline">\(=\frac{12}{32(32)}[\frac{55^2}{8}+\frac{132.5^2}{8}+\frac{145^2}{7}+\frac{163.5^2}{8}]-3(32)\)</span></p>
<p><span class="math inline">\(=11.876\)</span></p>
<table>
<thead>
<tr class="header">
<th align="center">Pond 1</th>
<th align="center">Pond 2</th>
<th align="center">Pond 3</th>
<th align="center">Pond 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">7.68 (1)</td>
<td align="center">7.71 (6*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.71 (6*)</td>
</tr>
<tr class="even">
<td align="center">7.69 (2)</td>
<td align="center">7.73 (10)</td>
<td align="center">7.75 (16)</td>
<td align="center">7.71 (6*)</td>
</tr>
<tr class="odd">
<td align="center">7.70 (3.5*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.77 (18)</td>
<td align="center">7.74 (13.5)</td>
</tr>
<tr class="even">
<td align="center">7.70 (3.5*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.79 (22)</td>
</tr>
<tr class="odd">
<td align="center">7.72 (8)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.80 (23.5*)</td>
<td align="center">7.81 (26*)</td>
</tr>
<tr class="even">
<td align="center">7.73 (10*)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.81 (26*)</td>
<td align="center">7.85 (29)</td>
</tr>
<tr class="odd">
<td align="center">7.73 (10*)</td>
<td align="center">7.80(23.5*)</td>
<td align="center">7.84 (28)</td>
<td align="center">7.87 (30)</td>
</tr>
<tr class="even">
<td align="center">7.76 (17)</td>
<td align="center">7.81 (26*)</td>
<td align="center"></td>
<td align="center">7.91 (31)</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th align="center">n<sub>1</sub> =8</th>
<th align="center">n<sub>2</sub> =8</th>
<th align="center">n<sub>3</sub> =7</th>
<th align="center">n<sub>4</sub> =8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">R<sub>1</sub> =55</td>
<td align="center">R<sub>2</sub> =132.5</td>
<td align="center">R<sub>3</sub> =145</td>
<td align="center">R<sub>4</sub> =163.5</td>
</tr>
</tbody>
</table>
<p>*tied ranks</p>
<p><span class="math inline">\(\sum t=\sum (t^3_i-t_i)\)</span></p>
<p><span class="math inline">\(\sum t=(2^3-2)+(3^3-3)+(3^3-3)+(4^3-4)+(3^3-3)+(2^3-2)+(3^3-)\)</span></p>
<p><span class="math inline">\(\sum t=168\)</span></p>
<table>
<thead>
<tr class="header">
<th align="center">Pond 1</th>
<th align="center">Pond 2</th>
<th align="center">Pond 3</th>
<th align="center">Pond 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">7.68 (1)</td>
<td align="center">7.71 (6*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.71 (6*)</td>
</tr>
<tr class="even">
<td align="center">7.69 (2)</td>
<td align="center">7.73 (10)</td>
<td align="center">7.75 (16)</td>
<td align="center">7.71 (6*)</td>
</tr>
<tr class="odd">
<td align="center">7.70 (3.5*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.77 (18)</td>
<td align="center">7.74 (13.5)</td>
</tr>
<tr class="even">
<td align="center">7.70 (3.5*)</td>
<td align="center">7.74 (13.5*)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.79 (22)</td>
</tr>
<tr class="odd">
<td align="center">7.72 (8)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.80 (23.5*)</td>
<td align="center">7.81 (26*)</td>
</tr>
<tr class="even">
<td align="center">7.73 (10*)</td>
<td align="center">7.78 (20*)</td>
<td align="center">7.81 (26*)</td>
<td align="center">7.85 (29)</td>
</tr>
<tr class="odd">
<td align="center">7.73 (10*)</td>
<td align="center">7.80(23.5*)</td>
<td align="center">7.84 (28)</td>
<td align="center">7.87 (30)</td>
</tr>
<tr class="even">
<td align="center">7.76 (17)</td>
<td align="center">7.81 (26*)</td>
<td align="center"></td>
<td align="center">7.91 (31)</td>
</tr>
</tbody>
</table>
<table>
<thead>
<tr class="header">
<th>n<sub>1</sub> =8</th>
<th>n<sub>2</sub> =8</th>
<th>n<sub>3</sub> =7</th>
<th>n<sub>4</sub> =8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R<sub>1</sub> =55</td>
<td>R<sub>2</sub> =132.5</td>
<td>R<sub>3</sub> =145</td>
<td>R<sub>4</sub> =163.5</td>
</tr>
</tbody>
</table>
<p>*tied ranks</p>
<p><span class="math inline">\(\sum t=\sum (t^3_i-t_i)\)</span></p>
<p><span class="math inline">\(\sum t=(2^3-2)+(3^3-3)+(3^3-3)+(4^3-4)+(3^3-3)+(2^3-2)+(3^3-)\)</span></p>
<p><span class="math inline">\(\sum t=168\)</span></p>
<p><span class="math inline">\(C=1-\frac{\sum t}{N^3-N}=1-\frac{168}{31^3-31}=1-\frac{168}{29760}=0.9944\)</span></p>
<p><span class="math inline">\(H_c=\frac{H}{C}=\frac{11.876}{0.9944}=11.943\)</span></p>
<p><span class="math inline">\(\nu=k-1=3\)</span></p>
<p><span class="math inline">\(F=\frac{(N-k)H_c}{(k-1)(N-1-H_c)}=\frac{(31-4)(11.943)}{(4-1)(31-1-11.943)}=5.95\)</span></p>
<p><span class="math inline">\(F_{0.05(1),3,26}=2.98\)</span></p>
<p>Reject H<sub>0</sub></p>
</div>
</div>
<div id="logistic-regression" class="section level1">
<h1><span class="header-section-number">6</span> Logistic Regression</h1>
<div id="when-and-why-do-we-use-logistic-regression" class="section level2">
<h2><span class="header-section-number">6.1</span> When and why do we use logistic regression?</h2>
<p>In some cases the response rariable (or dependent variable, DV) is binomially distributed.</p>
<p>We need an alternative approach because having a categorical outcome variable violates the assumption of linearity in normal regression.</p>
<p>Suppose we want to predict whether someone is diabetic by evaluating plasma glucose . We could plot the relations between the two variables as we customarily do in regression.</p>
<p>Note: It is customary to code a binary DV either 0 or 1.</p>
<pre><code>##     1     2 
## &quot;neg&quot; &quot;pos&quot;</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>Here we code one DV as 1 and the other as 0 (positive and negative for diabetes).</p>
<p>If we code like this, then the mean of the distribution is equal to the proportion of 1’s in the distribution.</p>
<pre class="r"><code>library(tidyverse)
library(caret)
theme_set(theme_bw())


# Load the data and remove NAs
data(&quot;PimaIndiansDiabetes2&quot;, package = &quot;mlbench&quot;)
PimaIndiansDiabetes2 &lt;- na.omit(PimaIndiansDiabetes2)

# Number positive
length(which(PimaIndiansDiabetes2$diabetes == &quot;pos&quot;))</code></pre>
<pre><code>## [1] 130</code></pre>
<pre class="r"><code># Number negative
length(which(PimaIndiansDiabetes2$diabetes == &quot;neg&quot;))</code></pre>
<pre><code>## [1] 262</code></pre>
<pre class="r"><code># Total number
length((PimaIndiansDiabetes2$diabetes))</code></pre>
<pre><code>## [1] 392</code></pre>
<p>For example if there are 100 people in the distribution and 30 of them are coded 1, then the mean of the distribution is 0.30, which is the proportion of 1s.</p>
<p>The mean of the distribution is also the probability of drawing a person labeled as 1 at random from the distribution.</p>
<p>That is, if we grab a person at random from our sample of 100 that I just described, the probability that the person will be a 1 is 0.30.</p>
<p>Therefore, proportion and probability of 1 are the same in such cases. The mean of a binary distribution so coded is denoted as <em>P</em>, the proportion of 1s. The proportion of zeros is (1-<em>P</em>),which is sometimes denoted as <em>Q</em>.</p>
<p>$P = $ numer of ‘ones’</p>
<p><span class="math inline">\(Q = 1 - P\)</span></p>
<p>The variance of such a distribution is <span class="math inline">\(P \times Q\)</span>, and the standard deviation is <span class="math inline">\(\sqrt{PQ}\)</span>.</p>
</div>
<div id="when-and-why" class="section level2">
<h2><span class="header-section-number">6.2</span> When and Why?</h2>
<p>To predict an outcome variable that is categorical from one or more categorical or continuous predictor variables.</p>
<p>In this class we will focus on regression with one predictor.</p>
<p><span class="math inline">\(P=\frac{1}{1+e^{-(b_0+b_1X_)}}\)</span></p>
</div>
<div id="what-are-we-predicting" class="section level2">
<h2><span class="header-section-number">6.3</span> What are we predicting?</h2>
<p>In the equation above:</p>
<ul>
<li><p><em>P</em> is the probability of a 1 (the proportion of 1s, the mean of Y),</p></li>
<li><p><em>e</em> is the base of the natural logarithm (about 2.718),</p></li>
<li><p>and <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> are the parameters of the model.</p></li>
</ul>
<p>The value of <span class="math inline">\(b_0\)</span> yields <em>P</em> when <em>X</em> is zero, and <span class="math inline">\(b_1\)</span> adjusts how quickly the probability changes with changing X a single unit.</p>
<p>The relation between <em>X</em> and <em>P</em> is nonlinear.</p>
<pre class="r"><code>b0 = rep(-10,3)
b1 = c(0.14,0.25,0.54)
x = seq(1,100)
plot(x, 1/(1+exp(-(b0[1] + b1[1]*x))), type = &#39;n&#39;)
lines(x, 1/(1+exp(-(b0[1] + b1[1]*x))), col = &quot;red&quot;, lwd = 2)
lines(x, 1/(1+exp(-(b0[1] + b1[2]*x))), col = &quot;blue&quot;, lwd = 2)
lines(x, 1/(1+exp(-(b0[1] + b1[3]*x))), col = &quot;green&quot;, lwd = 2)
legend(&#39;bottomright&#39;, legend = b1, col = c(&#39;red&#39;, &#39;blue&#39;, &#39;green&#39;), lwd = rep(2, 3))</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<pre class="r"><code>b0 = c(-5,-10,-15)
b1 = rep(0.25,3)
x = seq(1,100)
plot(x, 1/(1+exp(-(b0[1] + b1[1]*x))), type = &#39;n&#39;)
lines(x, 1/(1+exp(-(b0[1] + b1[1]*x))), col = &quot;red&quot;, lwd = 2)
lines(x, 1/(1+exp(-(b0[2] + b1[2]*x))), col = &quot;blue&quot;, lwd = 2)
lines(x, 1/(1+exp(-(b0[3] + b1[3]*x))), col = &quot;green&quot;, lwd = 2)
legend(&#39;bottomright&#39;, legend = b0, col = c(&#39;red&#39;, &#39;blue&#39;, &#39;green&#39;), lwd = rep(2, 3))</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
</div>
<div id="fitting-the-model" class="section level2">
<h2><span class="header-section-number">6.4</span> Fitting the Model</h2>
<div id="approach-1---ss" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Approach 1 - SS</h3>
<p>A loss function is a measure of fit between a mathematical model of data and the actual data.</p>
<p>We choose the parameters of our model to minimize the sum of squares residual.</p>
</div>
<div id="approach-2---likelihood" class="section level3">
<h3><span class="header-section-number">6.4.2</span> Approach 2 - Likelihood</h3>
<p>The log-likelihood statistic</p>
<ul>
<li>Analogous to the residual sum of squares in multiple regression</li>
<li>It is an indicator of how much unexplained information there is after the model has been fitted.</li>
<li>Large values indicate poorly fitting statistical models.</li>
</ul>
</div>
</div>
<div id="the-odds-ratio" class="section level2">
<h2><span class="header-section-number">6.5</span> The Odds Ratio</h2>
<p>Suppose we only know a person’s height and we want to predict whether that person is male or female.</p>
<p>We can talk about the probability of being male or female, or we can talk about the odds of being male or female.</p>
<p>Let’s say that the probability of being male at a given height is .90. Then the odds of being male would be:</p>
<p><span class="math inline">\(\mbox{odss ratio}=\frac{P}{1-P}\)</span></p>
<p>Odds can also be found by counting the number of people in each group and dividing one number by the other.</p>
<p>In our example, the odds would be 0.90/0.10 or 9 to one.</p>
<p>Now the odds of being female would be 0.10/0.90 or 1/9 or 0.11. This asymmetry is unappealing, because the odds of being a male should be the opposite of the odds of being a female.</p>
<p>So, we calculate the ‘log odds’</p>
<p>We can take care of this asymmetry though the natural logarithm, ln.</p>
<p>The natural log of 9 is 2.217, ln(0.9/0.1)=2.217.</p>
<p>The natural log of 1/9 is -2.217, ln(.1/.9)=-2.217.</p>
<p>So the log odds of being male is exactly opposite to the log odds of being female.</p>
<p>The natural log function looks like this:</p>
<pre class="r"><code>x = seq(0,10, by = 0.1)
plot(x, log(x), xlab = &#39;X, the odds&#39;, ylab = &#39;ln X (ln odds)&#39;, type = &#39;n&#39;)
lines(x, log(x), lwd = 3)
abline(h = 0)
abline(v = 1)</code></pre>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Note that the natural log is zero when X is 1.</p>
<p>When X is larger than one, the log curves up slowly.</p>
<p>When X is less than one, the natural log is less than zero, and decreases rapidly as X approaches zero.</p>
<p>When P = 0.50, the odds are .50/.50 or 1, and ln(1) = 0.</p>
<p>If P is greater than .50, ln(P/(1-P) is positive; if P is less than .50, ln(odds) is negative.</p>
<p>A number taken to a negative power is one divided by that number, e.g. e-10 = 1/e10.</p>
<p>A logarithm is an exponent from a given base, for example ln(e10) = 10.</p>
<p>Indicates the change in odds resulting from a unit change in the predictor.</p>
</div>
<div id="back-to-logistic-regression" class="section level2">
<h2><span class="header-section-number">6.6</span> Back to logistic regression</h2>
<p>In logistic regression, the dependent variable is a logit, which is the natural log of the odds, that is:</p>
<p><span class="math inline">\(log(odds) = logit(P)\)</span></p>
<p><span class="math inline">\(log(odds) = ln(\frac{P}{1-P})\)</span></p>
<p>So a logit is a log of odds and odds are a function of P, the probability of a 1. In logistic regression, we find:</p>
<p><span class="math inline">\(logit(P) = b_0 + b_1X\)</span></p>
<p><span class="math inline">\(ln(\frac{P}{1-P}) = b_0 + b_1X\)</span></p>
<p><span class="math inline">\(\frac{P}{1-P} = e^{b_0 + b_1X}\)</span></p>
<p><span class="math inline">\(P = \frac{e^{b_0 + b_1X}}{1-e^{b_0 + b_1X}}\)</span></p>
</div>
<div id="full-worked-example" class="section level2">
<h2><span class="header-section-number">6.7</span> Full worked example:</h2>
<p>Suppose that we are working with some doctors on heart attack patients. The dependent variable is whether the patient has had a second heart attack within 1 year (yes = 1). We have two independent variables, one is whether the patient completed a treatment consistent of anger control practices (yes=1). The other IV is a score on a trait anxiety scale (a higher score means more anxious).</p>
<pre><code>##    Person 2nd Heart Attack Treatment of Anger Trait Anxiety
## 1       1                1                  1            70
## 2       2                1                  1            80
## 3       3                1                  1            50
## 4       4                1                  0            60
## 5       5                1                  0            40
## 6       6                1                  0            65
## 7       7                1                  0            75
## 8       8                1                  0            80
## 9       9                1                  0            70
## 10     10                1                  0            60
## 11     11                0                  1            65
## 12     12                0                  1            50
## 13     13                0                  1            45
## 14     14                0                  1            35
## 15     15                0                  1            40
## 16     16                0                  1            50
## 17     17                0                  0            55
## 18     18                0                  0            45
## 19     19                0                  0            50
## 20     20                0                  0            60</code></pre>
<p>Now let’s look at the logistic regression, for the moment examining the treatment of anger by itself, ignoring the anxiety test scores.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<pre><code>## 
## Call:  glm(formula = data.$`2nd Heart Attack` ~ data.$`Treatment of Anger`, 
##     family = binomial)
## 
## Coefficients:
##                (Intercept)  data.$`Treatment of Anger`  
##                     0.5596                     -1.2528  
## 
## Degrees of Freedom: 19 Total (i.e. Null);  18 Residual
## Null Deviance:       27.73 
## Residual Deviance: 25.88     AIC: 29.88</code></pre>
<p>So, we can write the model, using the estimated parameters:</p>
<p><span class="math inline">\(P=\frac{1}{1+e^{-(-0.5596+1.2528\times X_)}}\)</span>.</p>
<p>The intercept is the value of <span class="math inline">\(b_0\)</span>, in this case -.5596.</p>
<p>As usual, we are not terribly interested in whether a is equal to zero.</p>
<p>The value of <span class="math inline">\(b_1\)</span> given for Anger Treatment is -1.2528.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
</div>
<div id="lets-look-at-the-odds-ratio" class="section level2">
<h2><span class="header-section-number">6.8</span> Let’s look at the odds ratio:</h2>
<p><span class="math inline">\(odds = (\frac{P}{1-P})\)</span></p>
<p><span class="math inline">\(P=\frac{1}{1+e^{-(-0.5596+1.2528\times X_)}}\)</span>.</p>
<p><span class="math inline">\(odds = \frac{\frac{1}{1+e^{-(-0.5596+1.2528\times X_)}}}{1-\frac{1}{1+e^{-(-0.5596+1.2528\times X_)}}}\)</span></p>
<table>
<thead>
<tr class="header">
<th align="center">Heart Attack</th>
<th align="center">yes</th>
<th align="center">no</th>
<th align="center">total</th>
<th align="center"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">yes</td>
<td align="center">3</td>
<td align="center">7</td>
<td align="center">10</td>
<td align="center"></td>
</tr>
<tr class="even">
<td align="center">no</td>
<td align="center">6</td>
<td align="center">4</td>
<td align="center">10</td>
<td align="center"></td>
</tr>
<tr class="odd">
<td align="center">total</td>
<td align="center">9</td>
<td align="center">11</td>
<td align="center">20</td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>Now we can compute the odds of having a heart attack for the treatment group and the no treatment group.</p>
<p>For the treatment group, the odds are 3/6 = 1/2.</p>
<p>The probability of a heart attack is 3/(3+6) = 3/9 = 0.33.</p>
<p>The odds from this probability are 0.33/(1-.33) = 0.33/0.66 = 1/2.</p>
<p>The odds for the no treatment group are 7/4 or 1.75.</p>
<p>The odds ratio is calculated to compare the odds across groups.</p>
<p><img src="Linear_Models_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
